### PR TITLE
Renamed  Secret of the Stars (U)

### PR DESCRIPTION
**Pull request by himanshu007-creator**
this solves #618

### CODE REVIEW

**Comment by frederic-mahe** [comment]
Your solution to #618 is to remove the entire file, are you sure about that?

**Comment by tjanas** [comment]
This is the wrong way.

**Comment by tjanas** [comment]
I fixed it with a single commit. https://github.com/frederic-mahe/Hardware-Target-Game-Database/pull/621

**Comment by frederic-mahe** [comment]
The way you did it makes it difficult to check what changed exactly. It turns out that your pull request changes about 169 lines. You are missing the recent changes to that file, and the single change you were supposed to do disappeared in the process.

For future reference, I suggest you fork the repository, make a clone on a computer were you can edit large text files, push to your fork, and create a pull request from there.

**Comment by himanshu007-creator** [comment]
> The way you did it makes it difficult to check what changed exactly. It turns out that your pull request changes about 169 lines. You are missing the recent changes to that file, and the single change you were supposed to do disappeared in the process.
> 
> For future reference, I suggest you fork the repository, make a clone on a computer were you can edit large text files, push to your fork, and create a pull request from there.

Sure, i work in that manner generally, but due to some work i took the shortcut, thanks for correcting me @frederic-mahe ✨🙂

**Pull request closed without merging**
