### PR TITLE
[SNES] Add new Super Game Boy Beta unit and modify naming scheme.

### PR DESCRIPTION
**Pull request by birdybro**
I dumped a ROM of a newly discovered Super Game Boy beta unit (found in my old collection from childhood, dumped on a Retrode 2 as of yesterday).

https://imgur.com/a/T8qHkLR

Additionally I am proposing the following name changes to reflect ROM chip markings ( cross-posted to No-Intro as a proposal already --> https://forum.no-intro.org/viewtopic.php?f=6&t=4771 ):

`Super Game Boy (Japan, USA).sfc` renamed to `Super Game Boy (Japan, USA) (SYS-SGB-NT).sfc` to reflect ROM chip markings from no-intro --> https://datomatic.no-intro.org/index.php?page=show_record&s=49&n=2683  - Note pcb front image on entry from dumper bikerspade --> https://datomatic.no-intro.org/sources%20media/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/20190430_103300_2683_pcb_front.jpeg

No change to `Super Game Boy (Japan, USA) (Rev 1).sfc` as the entry on No-Intro doesn't have much information at all, and this was just grandfathered from it's name there.

`Super Game Boy (Japan, USA) (Beta) (1994-03-23).sfc` to `Super Game Boy (Japan, USA) (Prototype) (SGB-SYST) (1994-03-23).sfc` as it's clearly a Prototype unit (has a generic ST Microcontroller rom chip, not a nintendo one), and the rom marking is SGB-SYST on the label --> https://datomatic.no-intro.org/sources%20media/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/20150516_114434_3603_pcb_front.jpg

`Super Game Boy (World) (Rev 2).sfc` to `Super Game Boy (World) (SYS-SGB-2).sfc` due to the markings on the ROM chip --> https://datomatic.no-intro.org/sources%20media/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/20100124_134709_2685_pcb_front.jpg

`Super Game Boy 2 (Japan).sfc` to `Super Game Boy 2 (Japan) (SYS-SGB2-10).sfc` due to markings on the ROM chip --> https://datomatic.no-intro.org/sources%20media/Nintendo%20-%20Super%20Nintendo%20Entertainment%20System/20181121_203325_2686_pcb_front.jpg

The previous naming scheme didn't make much sense considering these are boot ROMs and revisions aren't marked as revisions anywhere in such a way.

### CODE REVIEW

**Comment by tjanas** [comment]
I prefer that it not be added or existing names changed until it percolates it way thru  no-intro. Do you own a Super Nt, and if so, could you trying dumping with that as well as a sanity check? Adding the rom chip IDs instead of Rev 1, Rev 2, etc is the old deprecated no-intro naming scheme. I doubt they will go back to that.

**Comment by birdybro** [comment]
I do not own a Super NT. The ROM is being looked over by a few people in the know in case something is wrong. Is there anything suspected to be wrong with a Retrode 2 dumping a Super Game Boy boot ROM?

**Comment by birdybro** [comment]
Just FYI

I talked with pinobatch who is knowledgeable about these things, and he says that the ROM on an SGB is just a normal SNES LoROM, so I have no reason to suspect the Retrode 2 would treat it different than any of the other SNES cartridges I dumped yesterday (pictured below) which all matched the No-Intro database entries:
image

**Comment by frederic-mahe** [comment]
Nice work @birdybro , a very detailed and well documented pull request. However, I concur with @tjanas and I suggest to wait for your changes to be pulled in by No-Intro. Our policy is to follow No-Intro's naming scheme whenever possible, our added value is in the organization of all these files.

**Comment by birdybro** [comment]
I will change the naming scheme once I find out what they are renaming mine to. I haven't heard back yet on the proposed name change specifically, and the SNES database is locked currently so when I went to check today it was not available :P

I'll try to remember to finish this up with correct naming schemes.

**Comment by birdybro** [comment]
Closing this as they still haven't submitted my entry to No-Intro DB and my fork got all screwed up again for some reason back then.

**Pull request closed without merging**
