### PR TITLE
NES: Update ED N8 & PowerPak SMDB

### PR DESCRIPTION
**Pull request by maniac79**
Huge Update!
All base folders are based on following No-Intro specs:
Nintendo - Nintendo Entertainment System (20200329-092100).zip

Note: seems [Nintendo - Nintendo Entertainment System (20200405-041607) [headered] is in the making but not ready yet!

**General cleanup**
Renamed all instances of T-Eng -> T+Eng

**Folder updates**
1 US A-Z -> Contain exactly all released retail releases [677 ROMs] in the latest revision released at the time, later re-releases (e.g. Gamecube, WiiWare -> Revisions)

2 Europe A-Z -> Contain exactly all released retail releases in both PAL regions [348 ROMs] in their latest revision released at the time in English language (where applicable, Deja Vu for example was only released in Swedish in PAL!)

2 Japan A-Z -> Should contain all released retail releases from this region but I'm not 100% sure, also only in their latest available revisions released at the time

2 Other regions -> Only 2 ROMs (1 Asia, 1 Canada)

2 Unlicensed A-Z -> Also based on what's available in the No-Intro set. Added those files which were in the previous pack to make sure nothing's missed.
I merged the PAL releases and NTSC releases because otherwise people would need to know exactly what to look for and I believe that's not feasible for the "mainstream". Slightly renamed the Multicarts folder.

3 Famicom Disk System -> Didn't touch (maybe updated a few file names, unsure)

3 Famicom Disk System for PowerPak -> Didn't touch (maybe updated a few file names, unsure)

3 Nintendo Switch -> New folder which I didn't know where else to place. There is one NES ROM which presumably works on real hardware that was recently released on Nintendo Switch (Steins;Gate (USA) (Nintendo Switch).nes).

3 Nintendo VS. System Arcade -> Didn't touch (maybe minor file name updates)

3 NSF Music for PowerPak -> Didn't touch (maybe minor file name updates)

3 PlayChoice-10 Arcade -> Didn't touch (maybe minor file name updates)

4 Betas, Prototypes, Revisions -> Also based on what's available in the No-Intro set. Added those files which were in the previous pack to make sure nothing's missed.
I also added a "Competitions" sub-folder to put the Nintendo World Championship ROM in.

4 Game Series Collections ->  -> Also based on what's available in the No-Intro set. Added those files which were in the previous pack to make sure nothing's missed. A lot of spelling errors were corrected as well plus other things, like:
1. Top 100 List - satoshimatrix.wordpress.com was missing rank #37
2. 4 Game Series Collections\Chronological\Famicom 1986 contained Dig Dug 2 but Dig Dug (1) is correct.
I removed following folders:
'4 Game Series Collections\Miscellaneous\2 Player Co-Op' (felt redundant, same content as '4 Game Series Collections\Multiplayer\Sort By - 2 Player Co-Op')
'4 Game Series Collections\Genre\Light Gun Zapper' (felt redundant, same content as '4 Game Series Collections\Accesories & Add-Ons\Light Gun Zapper')
I also removed clones in different folders, for example:
'4 Game Series Collections\Genre\Puzzle\*' Mario & Yoshi (EU clone of US Yoshi) + Dynablaster (EU clone of US Bomberman 2)
'D:\SMDB\01. ROMs\N8 SMDB Rework\Nintendo - Nintendo Entertainment System\4 Game Series Collections\x Genre\x Sports\Skiing & Snowboarding' Snowboard Challenge (EU clone of US Heavy Shreddin')
Also:
1. I added the correct NES/Famicom Mini ROMs (as per NAND-Dumps available online)
2. I added the 'Regions' sub-folder

4 Hacks, 4 Homebrew and 4 Translations -> Left mostly untouched, I corrected a few spelling mistakes and removed dupes.

5 Tools & Service Test Carts -> Based on No-Intro ROM sets and added ROMs which were availble in the previous pack and are not in No-Intro

Unsupported -> Didn't touch

**Observations**

Hashes in '3 Famicom Disk System for PowerPak' are different from hashes in '3 Famicom Disk System' but file names are the same (for many files).
I don't know enough about the PowerPak to understand why it's like that but assume this has a reason (the Disk games probably have to be patched to work on the PowerPak?).
But shouldn't these files then have distinct file names?

Also: It might be a good idea to base the Disk System folders on the latest No-Intro ROM specs in similar fashion as I did it for the cartridge based ROMs.
(There are a few .fds games in the subfolders such as 'Game Series Collections\*' which should then also be looked at.

There are some files with the same file names and different hashes.
Only some examples which I found and noted down:
1. Esper Dream (J) (Rev 1) [b] [T+Eng].fds
2. Ganbare Goemon 2 (J) [T+Eng_S.Crusaders].nes
3. Nazo no Kabe - Block Kuzushi (Japan) [b].fds

As well as multiple instances of translation hacks with various amounts of different hashes, some even by same group and same version of translation:
- Labyrinth [3x]
- Bio Senshi Dan - Increaser Tono Tatakai [3x]
- Nekketsu Kakutou Densetsu [3x]
- Dragon Ball Z II - Gekishin Freeza!! [Saiya] [2x]
- Kaijuu Monogatari (J) [T+Eng v1.0b_KingMike] [3x]
- Fushigi no Umi no Nadia (J) [T+Eng1.3_J2e] [2x]
- Majou Densetsu II -Daimashikyou Galious (J) [f1] [T+Eng v.31b_manipulate] [2x]
- Jajamaru Gekimaden - Maboroshi no Kinmajou (J) [2x]
- Ganbare Goemon 2 (J) [T+Eng_S.Crusaders] [2x]
- Heracles no Eikou 2 - Titan no Metsubou (J) [T+Eng_SpoonyBard]/[T+Eng v1.31_Toma] [2x] (Note: Looks like 2 different translation groups, but if you look at the Readme of the Spoony Bard's translation on Romhacking.com, the credit for v1.31 goes to Toma, so it seems to be the same thing?)
- Chaos World [3x]
- Dragon Ball Z - Kyoushuu! Saiya Jin (J) [T+Eng v1.1] + Dragon Ball Z - Kyoushuu! Saiya Jin (J) [T+Eng v1.1]_Alt
- Musashi no Bouken (J) [T+Eng.98_MadHacker+Gaijin] / Musashi no Bouken (J) [o1][T+Eng.98_MadHacker+Gaijin]
- Sted - Iseki Wakusei no Yabou (J) [T+Eng1.0_J2E] / Sted - Iseki Wakusei no Yabou [T+Eng_J2e]
- Banana Prince (G) [T+Eng v1.1a_KingMike].nes / Banana Prince [T+Eng1.1a_KingMike].nes
- Fushigi no Umi no Nadia (J) [T+Eng1.3_J2e].nes / Fushigi no Umi no Nadia (J) [T-Eng_J2e].nes
- Majou Densetsu II -Daimashikyou Galious (J) [f1] [T+Eng v.31b_manipulate].nes / Majou Densetsu II -Daimashikyou Galious (J) [f1][o1] [T+Eng v.31b_manipulate].nes
- Ganbare Goemon 2 (J) [T+Eng_StardustCrusaders]_Alt.nes / Ganbare Goemon 2 (J) [T+Eng_StardustCrusaders].nes
- Urusei Yatsura - Lum no Wedding Bell [T+Eng_Stardust Crusaders].nes / Urusei Yatsura - Lum no Wedding Bell [T+Eng_Stardust Crusaders]_Alt.nes
- Yume Penguin Monogatari [T+Eng_Vice].nes / Yume Penguin Monogatari (J) [T+Eng v1.01_Vice].nes
- R-Type (Magic Dragon Hack) v1 pacnsacdave.nes -> many different files with same name but 2 different hashes -> one version may include a translation hack which the other doesn't?
- Egypt (J) [T+Eng v1_Dodgy].nes / Egypt (J) [T+Eng_Dodgy].nes
- Minna no Taabou no Nakayoshi Daisakusen (J) [T+Eng_Suicidal].nes / Minna no Taabou no Nakayoshi Daisakusen (J) [T+Eng v1.01_Suicidal].nes
- Captain Tsubasa Vol. II - Comback Of Twins K Edition (Hack).nes [2]
- Chuugoku Taitei (Asia) (Ja) (Unl).nes -> has 3 instances in 'unsupported' folders with different hash

Author and/or versions of many translations/hacks are missing in file names.

One special curious translation case:
Double Moon Densetsu: In previous pack the Beta4 by Kiwibonga was used in the Game Series Collection.
This patch is listed as "Unfinished" on ROMhacking.net.
Then there are 2 files with the same hash in '4 Hacks' and '4 Translations' but without any info on version or auther of the patch (Legend of Double Moon, The.nes).
This game has recently received an updated translation patch according to ROMhacking.net: 1.02 by Stardust Crusaders & aishsha.
For now, I have used the Beta4 in the new pack as well but...

... what I propose for the Double Moon Densetsu translation:
- the reference to the two files 'Legend of Double Moon, The.nes' should be removed
- the Beta4 by Kiwibonga should be kept in '4 Translations' for documentation purpose
- the 1.02 by Stardust & aishsha should be added to '4 Translations'
- all references to Beta4 should be replaced by references to 1.02

Other presumably updated translation hacks I came across:
Final Fantasy II (J)
- has received an updated translation patch from Chaos Rush beginning of April (2.0)
- add to '4 Translations/English A-K/'
- replace current translation patches instances in '4 Game Series Collections/*' and '4 Translations/Selections' (where applicable) with it
https://www.romhacking.net/translations/2656/

Final Fantasy III (J)
- has another, more recent translation patch (v1.3_Chaos Rush)
- add latest patch to '4 Translations/English A-K/'
- replace current translation patches instances in '4 Game Series Collections/*' and '4 Translations/Selections' (where applicable) with it
https://www.romhacking.net/translations/4760/

Tenchi o Kurau II - Shokatsu Koumei Den (J)
- has another, more recent translation patch (v1.12_Dark Force, Dynamic-Designs, Jair, Taskforce)
- add latest patch to '4 Translations/English L-Z/'
- replace current translation patches instances in '4 Game Series Collections/*' and '4 Translations/Selections' (where applicable) with it
https://www.romhacking.net/translations/116/

Wagyan Land 2 also received a more recent patch than what's in the pack now.

SD Gundam Gaiden - Knight Gundam Monogatari (J) (V1.0) [T+Eng0.10_Assassin_Productions]
- only in 4 Game Series Collections\Genre\Role Playing Games\All Role Playing Games
- should be checked if this ROM is good and/or if newer/better translation patches exist and the be added to the '4 Translations' folder

**Kaiketsu Yanchamaru 2 - Karakuri Land (J)**
There is one file in the pack: Kaiketsu Yanchamaru 2 - Karakuri Land (J) [T+Eng v1.01_Shadow] -> but this version isn't listed on ROMhacking.net
There is another file in the pack: Kaiketsu Yanchamaru 2 - Karakuri Land[T+Eng_D] -> what's the version?
And another file: Kaiketsu Yanchamaru 2 - Karakuri Land (J) [hFFE][T+Eng] -> author and version?

**Final note**
My observations don't give a complete picture, I think it's safe to assume there are many more issues which are the same or similar to the ones I noted above.

### CODE REVIEW

**Comment by tjanas** [comment]
@frederic-mahe @SmokeMonsterPacks @maniac79 i am a bit concerned about such a large update, it makes it very difficult to audit. Also, this needs to be compared with the [proposed changes by tjstogy](https://github.com/tjanas/EverDrive-Packs-Lists-Database/commit/faaaa612cdba03554070d7e70dded6b586f19496).

T-Eng should not blindly be changed to T+Eng unless you are confident it is the latest patch (T-Eng represents older patch, T+Eng represents latest).

I don't think a new directory called Competitions should be added to hold that one ROM.

I highly recommend not adding any NEW roms (e.g. Nintendo Switch) dumps as part of this. New no-intro additions we did not have before should be part of a future SMDB update, not this.

I will work on FDS eventually as I have done some considerable analysis on it, including the need for merged two-disk/4-side games and other unique cases.

Again, I think it is critical for you and tjstogy to reconcile any changes to Game Series Collections.

**Comment by maniac79** [comment]
> @frederic-mahe @SmokeMonsterPacks @maniac79 i am a bit concerned about such a large update, it makes it very difficult to audit. Also, this needs to be compared with the [proposed changes by tjstogy](https://github.com/tjanas/EverDrive-Packs-Lists-Database/commit/faaaa612cdba03554070d7e70dded6b586f19496).

Yeah, we knew that was coming and I hope there'll be a solution.

> T-Eng should not blindly be changed to T+Eng unless you are confident it is the latest patch (T-Eng represents older patch, T+Eng represents latest).

Agree and to be honest: I didn't know the rule that only the latest should be T+Eng and older ones T-Eng. :-/

> I don't think a new directory called Competitions should be added to hold that one ROM.

Yeah, I can relate. But where else to put it?

> I highly recommend not adding any NEW roms (e.g. Nintendo Switch) dumps as part of this. New no-intro additions we did not have before should be part of a future SMDB update, not this.

Out of 60 added ROM files, 6 are unknown in No-Intro. All others do verify against the latest No-Intro specs (I checked it today with a fresh DAT file).
Also, this is exactly the same process we did for Genesis Mini, so personally I don't see an issue here.

**Comment by tjanas** [comment]
What are the six additions that are not part of no-intro, and what are the additions that are? Something like that could be its own separate pull request, which would be easy to audit and approve and might be a good idea to do first, since now that I finally have a 100% complete current set which was a nightmare to construct.

In general, the scope of a pull request should be limited in focus.

**Comment by tjanas** [comment]
If you are refreshing translations, that should be its own pull request, and then it could be relatively easily to review and audit. One mega pull request like this is unwieldy and very difficult to sit down and review and make sure it is correct.

**Comment by frederic-mahe** [comment]
First of all, thank you @maniac79 for this huge effort to update the pack to the latest No-Intro!

Now, I am not sure how to proceed exactly. We have:
```
# additions
    224 EverDrive N8/1 US - A-F
    228 EverDrive N8/1 US - G-Q
    226 EverDrive N8/1 US - R-Z
    348 EverDrive N8/2 Europe - A-Z
   1066 EverDrive N8/2 Japan - A-Z
      2 EverDrive N8/2 Other Regions - A-Z
   1213 EverDrive N8/2 Unlicensed - A-Z
     40 EverDrive N8/3 Famicom Disk System
      1 EverDrive N8/3 NSF Music for PowerPak
      1 EverDrive N8/3 Nintendo Switch
    709 EverDrive N8/4 Betas, Prototypes, Revisions
   5638 EverDrive N8/4 Game Series Collections
     61 EverDrive N8/4 Hacks
    273 EverDrive N8/4 Translations
     10 EverDrive N8/5 Tools & Service Test Carts
      2 EverDrive N8/Unsupported

# deletions
    228 EverDrive N8/1 US - A-F
    233 EverDrive N8/1 US - G-Q
    231 EverDrive N8/1 US - R-Z
    373 EverDrive N8/2 Europe - A-Z
   1053 EverDrive N8/2 Japan - A-Z
      1 EverDrive N8/2 Other Regions - A-Z
   1265 EverDrive N8/2 Unlicensed - A-Z
     35 EverDrive N8/3 Famicom Disk System
      1 EverDrive N8/3 NSF Music for PowerPak
    521 EverDrive N8/4 Betas, Prototypes, Revisions
   4802 EverDrive N8/4 Game Series Collections
     58 EverDrive N8/4 Hacks
    276 EverDrive N8/4 Translations
      8 EverDrive N8/5 Tools & Service Test Carts
      2 EverDrive N8/Unsupported
```
I don't know if there is a way to break a pull request into smaller components. We are entering unknown git territory here. So, I am going to suggest a way to proceed that will ask some more work on your part @maniac79 , but it will make reviewing easier.

I suggest you grab or build a version of the pack using the current master SMDB. You can then replace one folder, `2 Unlicensed - A-Z` for example, with a copy of the corresponding folder from your updated set. If you parse the pack, it will create a new SMDB that will be different from the current one just for that folder `2 Unlicensed - A-Z`. Then you pull request, we review, we merge. Piecemeal.

Now, how far do you need to go into that folder-by-folder approach? I would say that folders numbered `4` are the trickiest, so you might want to break them into smaller components.

Take your time to think about it, maybe there is a smarter way to proceed. 

> T-Eng should not blindly be changed to T+Eng unless you are confident it is the latest patch (T-Eng represents older patch, T+Eng represents latest).

I didn't know that.

**Comment by maniac79** [comment]
The thing is, this update only makes sense in its entirety. If we go folder by folder, we will create more "dupes" with incorrect hashes/file names. Also, if you review only one folder (incl. its subfolders) you may feel I deleted some games without carrying them over but you'd find them in a different folder (e.g. revisions, dupes, ...). Of course, we can discuss this.

But I get your point and splitting things up into smaller chunks is possible and I'll come up with something that's hopefully easier to digest and still meaningful.

**Comment by maniac79** [comment]
> What are the six additions that are not part of no-intro, and what are the additions that are? 

For the NES Mini Classic it was only Excitebike that's not part of No-Intro (yet):
Excitebike (USA) **(Nintendo Classic Mini)**.nes
All other 29 NES Mini Classic ROMs are No-Intro verified and have their correct No-Intro file names.

For the Famicom there are 5 ROMs that aren't part of No-Intro (yet):
These have **(Nintendo Classic Mini Famicom)** in their file names.
All other 25 Classic Mini Famicom ROMs are No-Intro verified and have their correct No-Intro file names.

**Comment by SmokeMonsterPacks** [comment]
This is a huge update and is much appreciated. In the future, large updates should be broken up into smaller pushes. Individual ROM updates should be individual pushes, or done in smaller groups based on folders (Hacks, etc). That give us all some breathing room, and it doesn't make everything an all-or-nothing scenario, in which case it will be more likely to be rejected.

The official folders should contain the latest No-Intro revision, but they should also give preference to real hardware (or flash cart) fixed ROMs overtheir No-Intro counterparts. So I hope that the "everdrive fixed" roms still appear in the official folders. The mission of these lists is to be real hardware ready.

T-Eng should not be changed to T+Eng without cause. T-Eng indicates and outdated or unfinished translation, so those should be reverted. 

I would vote to reject this change pending changes. Instead it should be brought in piece by piece, like other submissions. It needs to be re-worked anyways, and this will give everyone the ability to understand the changes. A good place to start would be to push the individual Translations, Hacks, and Homebrew packs each as their own update. 

Also, just to give everyone a heads up. Once all of the updates are complete from everyone working on NES, the entire NES base of the list will be parsed from a new set of ROMs by The Great Hierophant, Rysha, et. al's massive NES 2.0 header rebuild. No-Intro's NES set is actually a huge mess due to their misunderstanding of NES headers.

**Comment by tjstogy** [comment]
@maniac79 Hey Dennis! As discussed, your updates, efforts, and enthusiasm to help the packs are super appreciated. Unbeknownst to you, while you were working on the N8 pack there was a lot of behind the scenes work by all of us on the same pack which ended up conflicting with most of your updates. Not your fault, of course, but simply poor timing and communication. Below are my comments on your proposed edits on the Game Series Collections, and I look forward to working with you in the future on these packs. 

> 4 Game Series Collections -> -> Also based on what's available in the No-Intro set. Added those files which were in the previous pack to make sure nothing's missed. A lot of spelling errors were corrected as well plus other things, like:
> 
>     1. Top 100 List - satoshimatrix.wordpress.com was missing rank #37

Good catch. Will fix.

>     2. 4 Game Series Collections\Chronological\Famicom 1986 contained Dig Dug 2 but Dig Dug (1) is correct.

Removed Chronological for now, as I don't have time to complete it and it seemed unnecessary specifically in it's uncompleted state. 

>        I removed following folders:
>        '4 Game Series Collections\Miscellaneous\2 Player Co-Op' (felt redundant, same content as '4 Game Series Collections\Multiplayer\Sort By - 2 Player Co-Op')

Agreed, This was removed in my latest update.

>        '4 Game Series Collections\Genre\Light Gun Zapper' (felt redundant, same content as '4 Game Series Collections\Accesories & Add-Ons\Light Gun Zapper')

This I was on the fence on- however, in regards to the NES specifically, Zapper games really are kind of a Genre IMO. Future systems, less so. When people think of the NES, they think of the Zapper. The games are small in size, and doubling up here doesn't seem extraneous to me. 

>        I also removed clones in different folders, for example:
>        '4 Game Series Collections\Genre\Puzzle*' Mario & Yoshi (EU clone of US Yoshi) + Dynablaster (EU clone of US Bomberman 2)
>        'D:\SMDB\01. ROMs\N8 SMDB Rework\Nintendo - Nintendo Entertainment System\4 Game Series Collections\x Genre\x Sports\Skiing & Snowboarding' Snowboard Challenge (EU clone of US Heavy Shreddin')

Good calls! Agreed. Per my own (silly) rules, I try to keep ONE game in the collections, and it's preferably the NTSC version of it whenever possibly. Otherwise, it clutters the folders. If flash cart devs were to implement something where you could select which regional version of the selected game you wanted via the UI, it would be a different story. We aren't there yet, and maybe won't be until there is demand. 

> As well as multiple instances of translation hacks with various amounts of different hashes, some even by same group and same version of translation:

This is something I agree is an issue. I'm hoping to find someone to help be a "translation guru" and help clean up these translation folders, as well as update the translations to reflect the romhacking.net updates. 


>     * only in 4 Game Series Collections\Genre\Role Playing Games\All Role Playing Games
> 
>     * should be checked if this ROM is good and/or if newer/better translation patches exist and the be added to the '4 Translations' folder

Yeah, this kind of stuff I need help with for sure. Suggestions are welcome.

**Comment by maniac79** [comment]
@All
Yeah, I sort of came out of nowhere because personally felt some of the packs needed some love. And I hope my sudden appearance is still welcome. :)
The NES is a console which is very dear to my heart and while I honestly don't have a good understanding of NES ROMs/ROM Headers, hacks and translations patches, I claim to have an excellent understanding of the NES game library (a friend and I released two books about PAL B NES games). And I have some IT knowledge (I was a software developer till 2011, now service delivery manager/team lead). Had to get acquainted with GIT first, I think my first Pull Request was strange in some ways but now I have gotten the hang to it.
When I first found the N8 pack I immediately had some ideas how I would change it for myself to improve it and when it was recently discovered that the current pack list was based mainly on 'non No-Intro ROMs' I wanted to help with this big update, cleaning up all the different hashes in the different subfolders. And because I firmly believe these updates would be beneficial to others as well, I felt like sharing them and here we are. :)
Maybe it was necessary to introduce myself like this to everyone and I'm really thankful for how warm I am welcomed here. Thanks everybody. :) And whatever the outcome of this, even if we completely scrap my ideas, I'm looking forward to hopefully be able to continue working with you on this in the future.

Before I go into detail, as discussed, I will split up my updates into smaller chunks and will start ASAP, probably today, because I really want to have this out of the way as this has become more time consuming than I initially imagined. I didn't keep track of this whole process but it's easily more than 20 hours by now.

@SmokeMonsterPacks 
> So I hope that the "everdrive fixed" roms still appear in the official folders. The mission of these lists is to be real hardware ready.
To be honest -> I had no clue some ROMs needed special fixing to run on an EverDrive. There was a huge N8/N8 Pro firmware update which added support for many new mappers, so I thought this was a way of the past?

If anyone has maybe 1-2 examples of games which needed fixing before, I'm happy to test them in my setup. Maybe you @tjanas, @frederic-mahe, @tjstogy?

> the entire NES base of the list will be parsed from a new set of ROMs by The Great Hierophant, Rysha, et. al's massive NES 2.0 header rebuild.
I'm REALLY looking forward to this update, awesome!

You can correct me if I'm wrong about this but I believe that my work is kind of supporting this by providing a better foundation to work with by removing duplicates and fixing incorrect file names throughout the complete SMDB.

@tjstogy 
> Good catch. Will fix. [Top 100 List - satoshimatrix.wordpress.com was missing rank #37]
Actually, this is already in this current Pull Request. I'll make sure this transfers over to a future Pull Request, so I don't think you'll have to worry.

I also noticed that there were 2 Top 10 lists (I forgot which ones, sorry) which have changed over time because people are still able to vote up till this day. I have updated these as well.

> Removed Chronological for now, as I don't have time to complete it and it seemed unnecessary specifically in it's uncompleted state.

Even though I put a lot of work into re-creating these folders, I'm somewhat relieved to read this because of the complexity (and sometimes even because release dates from 30+ years ago can be vague). I'll remove this part when I submit my Game Series Collections PR.

> Agreed, This was removed in my latest update. [removal of 2-Player Co-op folder in 4 Game Series Collections\Miscellaneous\]

👍 

> This I was on the fence on- however, in regards to the NES specifically, Zapper games really are kind of a Genre IMO. Future systems, less so. When people think of the NES, they think of the Zapper. The games are small in size, and doubling up here doesn't seem extraneous to me.

Sure, re-adding them won't be a big deal.

> Good calls! Agreed. Per my own (silly) rules, I try to keep ONE version of a game in the "Genre" collections, and it's preferably the NTSC version of it whenever possible.

I'm really happy that we have the same opinion here. 👍 This will also be in my future Game Series Collections PR.

> This is something I agree is an issue. I'm hoping to find someone to help be a "translation guru" and help clean up these translation folders.

Yeah, that would be great. For now I'll go through all my "mindless" T-Eng -> T+Eng changes and revert them.

**Comment by frederic-mahe** [comment]
> You can correct me if I'm wrong about this but I believe that my work is kind of supporting this by providing a better foundation to work with by removing duplicates and fixing incorrect file names throughout the complete SMDB.

Yes, I think we will build on your new organization, and fix headers or replace with ROMs with fixed headers.

> The thing is, this update only makes sense in its entirety. If we go folder by folder, we will [temporarily] create more "dupes" but with incorrect hashes/file names. Also, if you review only one folder (incl. its subfolders) you may feel I deleted some games without carrying them over but you'd find them in a different folder (e.g. revisions, dupes, ...).

On this point in particular, yes, stand-alone patches should be our goal. However, in that particular case it would require way too much work to go back, and I think we can accept partial patches. To make it clear that the patches should be taken as a whole, you could submit a series of numbered pull-requests with explicit names and comments. For instance:

> 1 - update and cleaning of European official ROMs
>
> Full European set, as of No-Intro (2020-03-29). Contains exactly all released retail releases in both PAL regions [348 ROMs] in their latest revision released at the time in English language (where applicable, Deja Vu for example was only released in Swedish in PAL!).
>
> Some ROMs were removed. A subsequent pull request will add them to different folders.

**Comment by frederic-mahe** [comment]
> The NES is a console which is very dear to my heart and while I honestly don't have a good understanding of NES ROMs/ROM Headers, hacks and translations patches, I claim to have an excellent understanding of the NES game library (a friend and I released two books about PAL B NES games).

I have a French book on the NES game library! Was your in German? It seems that enthusiasts in each European country made the same documentation effort :-)

**Comment by maniac79** [comment]
> Some ROMs were removed. A subsequent pull request will add them to different folders.

Can you please elaborate? Not sure if I understand.

> I have a French book on the NES game library! Was your in German? It seems that enthusiasts in each European country made the same documentation effort :-)

I am pretty sure that similar documentation efforts were made across the globe.
Our book is actually bilingual (German & English) and it gives a good general overview of the PAL B library but it doesn't focus on European sub-region specifics, such as France. I'm pretty sure your book contains information on distribution in France which we don't know much about. :)

**Comment by frederic-mahe** [comment]
> > Some ROMs were removed. A subsequent pull request will add them to different folders.

> Can you please elaborate? Not sure if I understand.

What I meant here is to pass the idea that the patch is partial (it doesn't show what happens in other folders). So that a patch reviewer can know that some of what has been removed will find its way back in another patch, for another folder.

**Comment by frederic-mahe** [comment]
@maniac79 I didn't forget your work on the NES pack. Direct merging is difficult due to the "header mess", which needs to be addressed first (@tjanas is on it). Once that will be done, I'll try to find a way to pull in your suggestions.

**Comment by tjanas** [comment]
Standalone [NES2.0 pack](https://github.com/frederic-mahe/Hardware-Target-Game-Database/blob/master/EverDrive%20Pack%20SMDBs/NES2.0%20SMDB.txt) was recently created that should have 100% correct & complete NES2.0 headers, and can be used directly with Analogue Nt Mini Noir and MiSTer.

**Pull request closed without merging**
