### PR TITLE
N64: add SM hacks

### PR DESCRIPTION
**Pull request by tjanas**
Add the following SM64 hacks:
SM64 - Skinned Mario Model Performance + O2 (Hack) v1 Nintendo 64 Wizard
SM64 - Skinned Performance + Smoke Fix + O2 DONE (Hack) v1 Nintendo 64 Wizard, v2 zoinknoise

Add the following translation:
Virtual Pro Wrestling 64 (J) T+Eng v1.77b Star Trinket

Renaming (hack) -> (Hack)

### CODE REVIEW

**Comment by Drakonas** [comment]
@tjanas Can you share where you got the "SM64 - Skinned Performance + Smoke Fix + O2 DONE (Hack) v1 Nintendo 64 Wizard, v2 zoinknoise" hack from? (e53e572ac571eed05d29673d0ab1396ad7a7f1e9ea9c4fd9859a64f771dcdf17)

I can find this anywhere or use the hacks to get a hash that matches.

**Comment by tjanas** [comment]
@Drakonas Smokemonster passed that one along to me, I’m not sure.

**Comment by Drakonas** [comment]
> @Drakonas Smokemonster passed that one along to me, I’m not sure.

"O2 Done" and "Skinned Performance" show no results on google when surrounded by double quotes with just "mario" added to the end... I have no idea what's used here but I can only make a couple guesses to the latter one.

I've found the [Skinned Model Mario Hack (AKA Smooth Mario)](https://www.romhacking.net/hacks/5367/). It's an xdelta patch, and supplies O2 optimized patches.

The [Smoke Fix Hack](https://www.romhacking.net/hacks/5008/) is more easy to assume, which is a BPS patch.

You should know as well as I that both of these formats do a checksum.

The notes for the Smoke Fix say that if you decompile, you can make the same change yourself by removing a couple patches from the build.

My guess is this hack has both the O2 patch ("Skinned Performance"?) of Skinned Mario and the Smoke Fix in place, along with whatever "O2 DONE means. Either someone manually patched them together, or somebody posted this patch somewhere that no longer exists. I can't find anything on this.

I don't think finding a complete HTGDB pack for a single rom is a good idea in order to build this pack, so I'm not sure keeping it makes sense, but that's just me. What are your thoughts?

I'm thinking of pushing a few updates to this pack too, but I'll add notes on that elsewhere, or in a PR. :)

**Comment by tjanas** [comment]
I agree that it should be reproducible. Perhaps a bps patch file could be produced and stored within this repo?

**Comment by frederic-mahe** [comment]
> I have uploaded a BPS patch within this repository so that the file can be reproduced

Good idea!

**Pull request merged**
