### PR TITLE
SNES: updated german translations

### PR DESCRIPTION
**Pull request by piyoeu**
Added most missing German translations from RHDN and https://snes-projects.de/filebase/index.php?category-file-list/5-super-nintendo-entertainment-system/

3 Ninjas Kick Back:
Version number corrected. 
Patch from https://web.archive.org/web/20161107085908/http://star-trans.net/?sub=proj&p=snes

Final Fantasy III:
There are two independent translation projects (Star-Trans, ManuLöwe) with complete translations. 
For the translation by ManuLöwe aka Cyan, also two variants exists: The 1.40a with a new serif font (which later received additional bugfixes), and the 1.40b with the original font (which did not).
I think that all three versions should be included.

Mega Man X 1/2/3:
I only kept the latest versions by Ice Man, who updated / ported the original translations by Sephiroth (G-Trans, Trans-X).
Two exceptions: I kept Sephiroth's translation of MMX1 (V1.0), just in case that Speedrunners might want to use that version. And I kept the completely different translation of MMX2.

Kirby's Ghost Trap: 
Alemanic Translations has released two translations with version number 1.00. I only kept the 1.00ALT, because the other is really crappy.

Super Mario World:
Better and more complete than the previous translation

A few files were left unchanged, because I did not find the original patch.
Also, a few translations are still missing, because I was unable to patch the ROMs.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
Thanks @piyoeu

**Comment by tjanas** [comment]
@piyoeu I tried downloading a few of these Final Fantasy III translations and I am unable to replicate your checksums. Also I feel that there are too many versions included:

SD2SNES/4 Translations/Non-English/German/Final Fantasy III (U) (V1.0) T+Ger v1.00 Star-Trans.sfc
SD2SNES/4 Translations/Non-English/German/Final Fantasy III (U) (V1.1) T+Ger v1.00 Star-Trans.sfc
SD2SNES/4 Translations/Non-English/German/Final Fantasy III (U) T+Ger v1.40a manuloewe, TitleScreen v1.0 Ice Man 2015.sfc	SD2SNES/4 Translations/Non-English/German/Final Fantasy III (U) T+Ger v1.40b manuloewe 2008.sfc

Can you please provide specific links to each of the translation patches?

**Comment by piyoeu** [comment]
**Final Fantasy III (U) (V1.0) T+Ger v1.00 Star-Trans.sfc**
Source: Final Fantasy III (USA).sfc
Patch: https://web.archive.org/web/20140403185925/http://star-trans.net/?sub=proj&info=snesff3
Apply to headered ROM

**Final Fantasy III (U) (V1.1) T+Ger v1.00 Star-Trans.sfc**
Source: Final Fantasy III (USA) (Rev 1).sfc
Patch: https://web.archive.org/web/20140403185925/http://star-trans.net/?sub=proj&info=snesff3
Apply to headered ROM

**Final Fantasy III (U) T+Ger v1.40a manuloewe 2008**
Source ROM: Final Fantasy III (USA).sfc
Patch: ff3dt140a.ips from https://www.romhacking.net/translations/1111/
Apply to headered ROM

**Final Fantasy III (U) T+Ger v1.40b manuloewe 2008**
Source ROM: Final Fantasy III (USA).sfc 
Patch: ff3dt140b.ips from https://www.romhacking.net/translations/1111/
Apply to headered ROM

**Final Fantasy III (U) T+Ger v1.40a manuloewe, TitleScreen v1.0 Ice Man 2015**
Source ROM: Final Fantasy III (USA) (Rev 1).sfc  
Patch: https://www.romhacking.net/translations/2341/
Apply to headerless ROM

All checksums I added to the SMDB are from headerless ROMs.

Final Fantasy III (U) (V1.0) T+Ger v1.00 Star-Trans.sfc probably can be removed.

**Comment by tjanas** [comment]
The patching notes for `Breath of Fire II (U) T+Ger v1.00 d4s.sfc` indicate the patch expects a source ROM "Breath of Fire II (U) [!].smc" with checksum C8B919AA. I assume this needed to be headered? No-intro [lists it](https://datomatic.no-intro.org/index.php?page=show_record&s=49&n=0295) as 67CDACC5. Even when adding 512 null padding bytes to Breath of Fire II (U) before patching it, this headered source ROM has a checksum of 4024CA16.

After patching this headered rom, the headered output has a checksum of E5BFD38E.
Finally, after removing the 512 byte header from this output to have a compliant SNES rom for real hardware, the checksum is 4FF8A0C8.

This does not seem to match the checksum in your commit for this translation.

**Comment by frederic-mahe** [comment]
> @piyoeu I tried downloading a few of these Final Fantasy III translations and I am unable to replicate your checksums. Also I feel that there are too many versions included:

@piyoeu explained in his pull request why there are three translations for Final Fantasy III. That seems ok to me. On the other hand, patching needs to be reproducible so clearly identifying the source ROM is very important for the pull request to be accepted.

@tjanas I forgot to enforce our policy regarding patches. To try and fix that I've started to create issue templates with clearer instructions. Would you like to edit what I did and to add new templates? I think you have editing rights ([documentation](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)).

**Comment by piyoeu** [comment]
So, I started to patch everything again and document the sources and if headers are required.
All hashes apply to raw roms without headers. 

The first part:

3 Ninjas Kick Back (U) T+Ger v0.99 Star-Trans.sfc

File Size: 2097152 Byte(s) (2.10 MB)
MD5: 227bdacc5f9e09f26bfdbb1f87d9a446
SHA1: 8b7f2439f6672c0d04a833830f46cb6ae8cefa17
SHA256: 4aee62c6e2e5e74248e89d6cbea8c3704cb31ae183fc2daf8d8224e7fff3503d
CRC32: 2dbe99f3

Source ROM: 2ffe8828480f943056fb1ab5c3c84d48a0bf8cbe3ed7c9960b349b59adb07f3b
Patch: https://web.archive.org/web/20140403185918/http://star-trans.net/?sub=proj&info=snes3nkb

Apply to headered ROM.

---

ActRaiser 2 (U) T+Ger v1.00 Alemanic Translations.sfc

File Size: 1572864 Byte(s) (1.57 MB)
MD5: 8a364febcfc353940bebf394a267c432
SHA1: 4505898d543a4b222643ab2093572b153045665b
SHA256: e72ed303d39815eb10bd739f383d354ebddd3e3c11dca6f4398b39248a5f14f6
CRC32: 31e51f0f

Source ROM: ActRaiser 2 (USA).sfc
Source SHA256: 71bdd448a30b88725864e55594ebb67a118b1f197a3f9e5dd39dbf23399efa15
Patch: https://snes-projects.de/filebase/index.php?file/91-actraiser-2-t-ger1-00-alemanic-translations/
       https://web.archive.org/web/2018*/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/ActRaiser-2-(U)-[T+Ger1.00_Alemanic-Translations].zip

Apply to headered ROM.

---

Addams Family, The - Pugsley's Scavenger Hunt (E) T+Ger v1.00 Star-Trans.sfc

File Size: 1048576 Byte(s) (1.05 MB)
MD5: a366f39c62dda6b91b6b4d5234472ad2
SHA1: cf8b16c580ddea693d5daa9d402def01747318fc
SHA256: 02d87941e4ed8c6395944cd7f3de5d74b550f00742bee49f6758e8ff1375f671
CRC32: 85765c8e

Source ROM: Addams Family, The - Pugsley's Scavenger Hunt (Europe).sfc
Source SHA256: bd5e7a6bc08f64d39c54204b82c6c156f144c03e13c890128588c5faa560659c
Patch: https://snes-projects.de/filebase/index.php?file/92-addams-family-the-pugsley-s-scavenger-hunt-t-ger1-00-star-trans/
       https://web.archive.org/web/20180508212340/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Addams-Family,-The---Pugsley-s-Scavenger-Hunt-(E)-[T+Ger1.00_Star-Trans].zip

Apply to headered ROM.

---

Alien 3 (E) T+Ger v0.99beta G-Trans.sfc

File Size: 1048576 Byte(s) (1.05 MB)
MD5: 39bef0237c142ac245cc8627d8b20158
SHA1: 151e6492294b0d3bcb1b4b8a13c43927c1015a90
SHA256: f2a8d136443cefad77502e809a4ba0431a4444ae7b4347d152f3bef7ba7da68f
CRC32: 98147f9d

Source SHA256: 65feac0ff8bf834bdb3f1eade09102496e1bd021a261ca05fc3a75983c357c84
Patch: https://snes-projects.de/filebase/index.php?file/95-alien-3-t-ger0-99-g-trans/
       https://web.archive.org/web/20180508212330/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Alien%203%20(E)%20[T+Ger0.99_G-Trans].zip

Apply to headered ROM.


---

Alien 3 (U) T+Ger v0.99beta G-Trans.sfc

File Size: 1048576 Byte(s) (1.05 MB)
MD5: de8fde75bfdde0356390a3b7a63a3570
SHA1: 952833b0a081119da7f50b108c5c444dd3d6f516
SHA256: 49720ae52751d6cf9e685b1783e95fe03c0348cd2f09089b7899f131900b322b
CRC32: 3770c038

Source ROM: Alien 3 (USA).sfc
Source SHA256: e637b8241d55ee334a3452888df5e30d72c520dbb55c498db1a984438bab3e55
Patch: https://snes-projects.de/filebase/index.php?file/95-alien-3-t-ger0-99-g-trans/
       https://web.archive.org/web/20180508212330/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Alien%203%20(E)%20[T+Ger0.99_G-Trans].zip
Apply to headered ROM.

The patch is intended for the EU rom, but works with the US version, too.

---

Alien vs Predator (U) T+Ger v1.00 snes-projects.sfc

File Size: 2097152 Byte(s) (2.10 MB)
MD5: 7a5a517970c1fc5369751329f9153e40
SHA1: 56b76ff408079b8c950664ae7060f11f735b8bbf
SHA256: 9943054c3d2b6b258399af90f5a0d6bf416bcba69048d3e0b28c9a7251d52c5d
CRC32: ab01152e

Source ROM: Alien vs. Predator (USA).sfc
Source SHA256: 05eb897d7696555790591c431c9d55a43ff9a1c12162443c17c5fcddfa5eb3c5
Patch: https://snes-projects.de/filebase/index.php?file/685-alien-vs-predator-t-ger1-00-snes-projects-de/

Apply to headerless ROM.

---

Animaniacs (U) T+Ger v1.00 Star-Trans.sfc

File Size: 1048576 Byte(s) (1.05 MB)
MD5: 753097de22aabe4a0290638133b86b1d
SHA1: f8e27631cdc67e4841e8a94c912bd48a5eacd5ff
SHA256: 28bc4847ab5f46c53f386439e558c0f24604f90cbc8bb9a3f9af84180ed5a257
CRC32: b23e0750

Source ROM: Animaniacs (USA).sfc
Source SHA256: 626f1fe52b0df0f8ede23f0062cd842321c8dabf14aefdca12e526876ecf383a
Patch: https://snes-projects.de/filebase/index.php?file/94-animaniacs-t-ger0-99-star-trans/
       https://web.archive.org/web/20180508212329/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Animaniacs%20(E)%20[T+Ger1.00_Star-Trans].zip

Apply to headered ROM.

---

Animaniacs (E) T+Ger v1.00 Star-Trans.sfc

File Size: 1048576 Byte(s) (1.05 MB)
MD5: 4d82461e69cf47dc958569af58b732cd
SHA1: f8bdce731fac5cefe552230be82aaa51f9e096ca
SHA256: ffe29ad81d678b53ceb89f876e2f9be957785f14f84f0b5476615344e7d8b70e
CRC32: 8022edea

Source ROM: Animaniacs (Europe).sfc
Source SHA256: 79ff74b758bb5df40d9fb6f830e9370de799c7a1423c482b2cc74eee78c55127
Patch: https://snes-projects.de/filebase/index.php?file/94-animaniacs-t-ger0-99-star-trans/
       https://web.archive.org/web/20180508212329/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Animaniacs%20(E)%20[T+Ger1.00_Star-Trans].zip
       
Apply to headered ROM.

---

Arkanoid - Doh It Again (E) T+Ger v1.00 Star-Trans.sfc

File Size: 524288 Byte(s) (524.29 KB)
Modified Date: 2021-03-30 18:20
MD5: aa1e9305b9b2e5215b22b2d01e468381
SHA1: dd4fe21375b55656d763914872aca615e42080fb
SHA256: 46ff9a202a3b98f16ff7c4c49c218e9319c637278d85abaeabffa7178742ad0f
CRC32: 1d0e7063

Source ROM: Arkanoid (Europe).sfc
Source SHA256: 333c6c76d518f496968f69cfc288b3995e735c308d153f3425b2100b9539abd6
Patch: https://web.archive.org/web/20140403185921/http://star-trans.net/?sub=proj&info=snesark

Apply to headered ROM.

---

Arkanoid - Do It Again (E) T+Ger v1.00 Alemanic Translation.sfc

File Size: 524288 Byte(s) (524.29 KB)
MD5: eafdb8cffc8e02a3c93c715546eddd87
SHA1: f4845d7cb23791f3a6db05ad27a3bd9442dcfb9e
SHA256: a97e041c2c577990e10759d59cd1e4a046bfd0adfedf9604d656b24d768f97a5
CRC32: 3b3cc5cd

Source ROM: Arkanoid (Europe).sfc
Source SHA256: 333c6c76d518f496968f69cfc288b3995e735c308d153f3425b2100b9539abd6
Patch: https://snes-projects.de/filebase/index.php?file/142-arkanoid-doh-it-again-t-ger1-00-alemanic-translations/
       https://web.archive.org/web/20180508212330/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Arkanoid%20-%20Doh%20It%20Again%20(E)%20[T+Ger1.00_Alemanic%20Translations].zip

Apply to headered ROM.

**Comment by piyoeu** [comment]
Bahamut Lagoon (J) T+Ger v1.20 snes-projects.sfc

File Size: 8388608 Byte(s) (8.39 MB)
MD5: 45992470e93d63787d4277fcc3279cc4
SHA1: 16fd93e6d8cfcb8fee87c2abea5706bc76f87083
SHA256: a4609ac1162369b245f65b7c37330cd72586a1223a0394be97ded7a3134ad2f4
CRC32: de54f596

Source ROM: Bahamut Lagoon (Japan).sfc / Bahamut Lagoon (J) [!].sfc
Source SHA256: a98eb5f0521746e6ce6d208591e86d366b6e0479d96474bfff43856fe8cfec12
Patch: https://snes-projects.de/filebase/index.php?file/567-bahamut-lagoon-t-ger1-20-snes-projects-de/
       https://web.archive.org/web/20180508212042/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Bahamut%20Lagoon%20(J)%20[T+Ger1.20_snes-projects.de].zip

Header required: no

---

Breath of Fire (USA)

File Size: 3145216 Byte(s) (3.15 MB)
MD5: 5530370f37b2712d9ae8e4ea8c45d44d
SHA1: 7a95575b6828ecb1353dbd5efafbf8d30e3739b2
SHA256: 63769b98f7c31b3e0784bc8773ac0e66a0725c64143e0e395f3d22741baa2cd5
CRC32: 3a772e5b

Source ROM: Breath of Fire (USA).sfc
Source SHA256: cbc496a7879ba78f32c51c3df4ba1a1a42f17d78d48a39ea9c709d1ad18cb8df
Patch: https://snes-projects.de/filebase/index.php?file/578-breath-of-fire-t-ger1-10-snes-projects-de/

Header required: yes

---

Breath of Fire II (U) T+Ger v1.0 d4s

File Size: 4194304 Byte(s) (4.19 MB)
MD5: 0accdccbc20017abfea8b54d1fe890e8
SHA1: b1b8b3b3c1b49f51dd444174ca7ed2c6c9ec9d67
SHA256: 60c4565e3369b9eb5ebc1ed1066c6bfae3c73660fa04122ba518c91fab2d45c2
CRC32: e9ca8f62

Source ROM: Breath of Fire II (USA).sfc / Breath of Fire II (U) [!].sfc
Source SHA256: fede9d4aec8c35ed11e2868c3c517bce53ee3e6af724085c92500e99e43e63de
Patch: https://www.romhacking.net/translations/1049/

Header required: yes

---

Cacoma Knight in Bizyland (U) T+Ger v0.95 Azelistic.sfc

File Size: 524288 Byte(s) (524.29 KB)
MD5: 8e55c26c184e68b8943eb98ce953f0e4
SHA1: 57241067d92a5eeb4abfa6f6fac7249ffadf8286
SHA256: 182779e8ceca0df11faa3667a97c84c2d1a0b6fd3d588ab626744b5e7e7ed3d9
CRC32: d9cf6380

Source ROM: Cacoma Knight in Bizyland (USA)
Source SHA256: a8294d449bbb8370816efe0374704e8af20dbbde9c19afe969d898528bc293d0
Patch: https://snes-projects.de/filebase/index.php?file/99-cacoma-knight-in-bizyland-t-ger0-95-azelistic/
    https://web.archive.org/web/20180508212340/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Cacoma%20Knight%20in%20Bizyland%20(U)%20[T+Ger0.95_Azelistic].zip

Header required: yes

---

Captain Tsubasa III - Koutei no Chousen (J) T+Ger v1.00 Star-Trans.sfc

File Size: 1048576 Byte(s) (1.05 MB)
MD5: 75f1256c4305db26fdbfa3f333e379ad
SHA1: 71bf29f2f3854ae7f74b7965a0394e91016e391f
SHA256: 1b53050725cbf49e2f2459496349f0479689f91026f047f69d6d6c910f62003e
CRC32: 2171d888

Source ROM: Captain Tsubasa III - Koutei no Chousen (Japan).sfc
Source SHA256: 6a299b99e0a55aec6669930dc622037d82d297e875630273c6cd6f05438aa3e6
Patch: https://web.archive.org/web/20140403185923/http://star-trans.net/?sub=proj&info=snestsu3

Header required: no

On the official translator's website, this is listed as version 1.00,
the included README however states version 0.71.

---

065b39c8ca69914e7e2138776b112fc8e2f20311560f308426c1e2503d82d799
Chrono Trigger (U) T+Ger v2.00rc manuloewe.sfc

File Size: 4194304 Byte(s) (4.19 MB)
MD5: f65b12390ca5c55ba37d2eefbc4f737b
SHA1: a38d8637a1db182bc63bd72c43c3a2a43d067c02
SHA256: 065b39c8ca69914e7e2138776b112fc8e2f20311560f308426c1e2503d82d799
CRC32: 6b3db159

Source ROM: Chrono Trigger (USA).sfc
Source SHA256: 06d1c2b06b716052c5596aaa0c2e5632a027fee1a9a28439e509f813c30829a9 
Patch: https://manuloewe.de/main/index.php?/pages/chronotrigger.html

Header required: no

This translation was released as 2.00rc in 2009 and rereleased as 2.00final
in 2012. The only difference is the patch format, which was moved from UPS
to xdelta.

There is also a second translation by a group named "Trans-Nation". 
However, that one is slightly incomplete and much older than the manulöwe
variant.

---

Clock Tower (J) T+Ger v2.01 RedScorpion.sfc

File Size: 4194304 Byte(s) (4.19 MB)
MD5: 977dc9c06b37daa587649ec305a558ff
SHA1: d878c8015c9fcaad0bd855144782104b4638989f
SHA256: ade5eae275870c8991abd92b5aafd88469121a7d5feac53a464d35f496e9a67b
CRC32: 0347539f

Source ROM: Clock Tower (Japan).sfc
Source SHA256: 5136488c9e87fcff6cec6fce3660c9e07a0909866a1e40336a4f9a93486b3b98
Patch: https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Clock%20Tower%20(J)%20[T+Ger2.01_RedScorpion].zip
       https://web.archive.org/web/20180508210416/https://lomengrace.de/snesprojects-mirror/patches/nintendo/snes/Clock%20Tower%20(J)%20[T+Ger2.01_RedScorpion].zip

Header required: no

**Pull request merged**
