### PR TITLE
Automatic base sorter for game backups

### PR DESCRIPTION
**Pull request by burabure**
Hey! I made this script to get a base sorting for any ROM packs that don't have a SMDB. I've tested this against a couple packs and have started building a MiSTer PSX one that I hope to submit in the future.

let me know if you need changes, I've tried to follow the guidelines on the repo/wiki/forums

### CODE REVIEW

**Comment by tjanas** [comment]
One thing to keep in mind with doing a regex on `USA` is that there are situations where the name of the actual game contains the USA string, but is not in the USA region.

Here's one real example I coincidentally came across today:
`Master EverDrive/2 Europe - A-Z/World Cup USA 94 (Europe, Brazil).sms`

**Comment by burabure** [comment]
@tjanas thanks for the feedback! I thought something like that would happen, so I used this regex for regions 
`' \([^\)]*USA[^\)]*\)'` so basically it only looks for the region name inside parenthesis

**Comment by tjanas** [comment]
Excellent, I'll have to give this script a spin!

**Comment by burabure** [comment]
Added discs folder support. useful for the Mister PSX core

**Comment by frederic-mahe** [comment]
Nice work @burabure ! I ran a few tests and it seems to work as expected. Your script should be very useful to quickstart future new packs

**Pull request merged**
