### PR TITLE
Doom 32X Resurrection hack updated to v2.0

### PR DESCRIPTION
**Pull request by blinard-BIOINFO**
Doom 32X Resurrection hack updated to v2.0. Update based on https://www.romhacking.net/hacks/6269/

### CODE REVIEW

**Comment by tjanas** [comment]
@blinard-BIOINFO your checksums are good but your entry is missing the filesize field

**Comment by blinard-BIOINFO** [comment]
@tjanas  fixed. My apologies, I just realized that you are now using file sizes for these roms too.

**Comment by frederic-mahe** [comment]
thanks @blinard-BIOINFO

**Comment by thiagoauler** [comment]
I do believe there is an error in this merge.
Every single ROM uses a format like this:
    32X/4 Homebrew & Hacks/Doom 32X Hacks/

But, Doom Resurrection uses a totally different format:
    Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/Doom 32X Hacks/

**Comment by tjanas** [comment]
> I do believe there is an error in this merge. Every single ROM uses a format like this: `32X/4 Homebrew & Hacks/Doom 32X Hacks/`
> 
> But, Doom Resurrection uses a totally different format: `Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/Doom 32X Hacks/`

Thank you! Fixed via https://github.com/frederic-mahe/Hardware-Target-Game-Database/commit/0f3403521050bd8c616bf8bbf28da86875cdf489

**Pull request merged**
