### PR TITLE
Mega Everdrive: Fix SHA-256 and revision of WWF RAW & Atari Lynx: Yostuna 2 Fix

### PR DESCRIPTION
**Pull request by birdybro**
While validating my own set I came across this. Check line 655 for instance and compare:

https://i.imgur.com/d0YnkUH.png

https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=1576

The previous entry doesn't seem to have been done by using the parse script or they forgot to change the SHA-256, since it's from the dubious no-intro dump. The naming has also been fixed since the confirmed good dump with the matching sha-1/md5/crc32 is actually REV 1.

### CODE REVIEW

**Comment by tjanas** [comment]
I will take care of reviewing this.

**Comment by birdybro** [comment]
Added fixes for atari lynx as per @tjstogy's request and confirmed. two-fer!

**Review by tjanas — APPROVED** [review]
I agree with this change, except I believe the filename should remain "WWF RAW (World)" and not "WWF RAW (World) (Rev 1)"

**Comment by birdybro** [comment]
Should be all fixed now.

**Comment by tjanas** [comment]
Thank you for finding these issues and fixing them!

**Pull request merged**
