### PR TITLE
Atari 2600: Add 4 Astroblast hacks from 2020

### PR DESCRIPTION
**Pull request by birdybro**
Source patches for new hacks:

http://www.romhacking.net/hacks/4876/

http://www.romhacking.net/hacks/4889/

http://www.romhacking.net/hacks/4890/

Also the "Give Me My Pancake!" entry was not in alphabetical order and my parse corrected that.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
Thanks @birdybro

**Comment by tjanas** [comment]
Do these work on real hardware? The patch notes only mention being tested in an emulator.

**Comment by birdybro** [comment]
> 
> 
> Do these work on real hardware? The patch notes only mention being tested in an emulator.

I did not test on original hardware, I tested on the MiSTer FPGA Atari 2600 core which often does not load roms that won't work on original hardware, but admittedly is not a 100% guarantee. If you'd like them to be removed prior to a test on O.G. hardware I can try and find someone who has the 2600 rom carts to be sure.

**Comment by tjanas** [comment]
If it works on mister, that is good enough for me. Thanks!

**Comment by frederic-mahe** [comment]
Please try to confirm that the ROMs run on original hardware. In the meantime, I don't think it is necessary to revert the commit.

**Pull request merged**
