### PR TITLE
PSX: move new translations into their own game directories

### PR DESCRIPTION
**Pull request by tjanas**
As noticed by @hotelvictorcharlie, some recent translations that were added were not placed in individual game directories. Directory name for Iru translation does not contain "..." to adhere to redump naming of the source bin/cue "[Iru! (Japan)](http://redump.org/disc/9501/)"

### CODE REVIEW

**Review by hotelvictorcharlie — APPROVED** [review]
LGTM but I wonder if we should remove the `...` from the beginning of Iru's filenames, as this will make them hidden on some filesystems.

**Comment by tjanas** [comment]
> LGTM but I wonder if we should remove the `...` from the beginning of Iru's filenames, as this will make them hidden on some filesystems.

Yes, we should; it is one reason why that's not part of the redump name. Removing the "..." would require a new cuesheet submission.

**Comment by hotelvictorcharlie** [comment]
> Yes, we should; it is one reason why that's not part of the redump name. Removing the "..." would require a new cuesheet submission.

I made this update and created a PR to merge it into this branch. So if you agree you can merge my PR here first, then merge the combined change into `master`.

**Comment by birdybro** [comment]
Sorry about just seeing this now. Thanks for finding a solution.

**Pull request merged**
