### PR TITLE
Mega Everdrive SMDB: Add Bio Hazard Battle Prototype

### PR DESCRIPTION
**Pull request by birdybro**
https://www.youtube.com/watch?v=CqTuPterSUo - From here, works on original hardware, brand new prototype! :)

### CODE REVIEW

**Comment by tjanas** [comment]
I've confirmed the checksum is good. Perhaps the name should be changed to be a Beta instead of a Prototype (the understanding is that a Prototype is a game that never gets released, but a Beta is a game that eventually is released). I see there is one [existing Beta](https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=0196) for this game named `Bio Hazard Battle (USA, Europe) (Beta) (August, 1992).md`, this could be named `Bio Hazard Battle (USA) (Beta) (1991).md` until no-intro determines a name for it.

**Comment by birdybro** [comment]
Good idea, changing that now.

**Comment by birdybro** [comment]
Fixed

**Comment by tjanas** [comment]
> Fixed. Date in header only showed "1991", no month, unless I'm missing something.

I noticed the same thing regarding the date in the header.

**Pull request merged**
