### PR TITLE
MiSTer: Update MSX Pack to version 20210131

### PR DESCRIPTION
**Pull request by birdybro**
NosferatuMSX pointed out that there was a newer version available than what was in the DB. Also the rom list and configs were removed for some reason, but they are part of the setup of the core. Since the readme comes with the pack that is out there, I have added a placeholder instead to maintain folder structure in the DB like other similar packs.

### CODE REVIEW

**Comment by tjanas** [comment]
Can you provide the sources to these cfg and txt files?

**Comment by birdybro** [comment]
[MSX.zip](https://github.com/frederic-mahe/Hardware-Target-Game-Database/files/8057295/MSX.zip)

From the readme's changelog

```
2020-01-31:
	- Sofarun 8.0 - several fixed have been implemented including MiSTer Support - no more swapping of prefered flash devices.
	- Added a demo section - the MSX core is not up to date with the latest components and some demos might not work correctly or at all
	- Updated a few disk games with new released translations
	- Added newly released ROM games (MSXDev2020 etc)
	- The boot logo has been changed to 'MiSTer' thanks to everyone who helped with this (KdL/HeWhoisRed etc) Logo might change in the neat future.
```

This is actually supposed to be 2021-01-31, it's a typo.

**Comment by birdybro** [comment]
Screenshot 2022-02-13 19-41-01

The correct latest image is shows a date of 2021-01-31 as well.

**Comment by tjanas** [comment]
Where did this MSX.zip come from that you uploaded?

**Comment by birdybro** [comment]
Archive.org from nosferatuMSX

**Comment by tjanas** [comment]
Found it: https://archive.org/details/release-2021-01-31 by [@nosferatumsx](https://archive.org/details/@nosferatumsx)

**Pull request merged**
