### PR TITLE
PSX: add Planet Laika translation

### PR DESCRIPTION
**Pull request by tjanas**
http://www.romhacking.net/translations/6451/
```
FILE "Planet Laika (J) T+Eng v1.3 Cargodin.bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
```

### CODE REVIEW

**Comment by tjanas** [comment]
@birdybro does this look ok?

**Comment by birdybro** [comment]
Checking now...

**Comment by birdybro** [comment]
What method did you use to patch this?

```
fc65d3498b7fdfb73666f1aabb81c2c5b7ebffb1d12e2b462f1780e9a1b621ff	PlayStation Redump Supplement/Planet Laika (J) T+Eng v1.2 Cargodin/Planet Laika (J) T+Eng v1.2 Cargodin.bin	b539a635fa76bf820f758595e8f53089c347e943	d0af82998cdd4bd60503dbc7b5663489	a21bc698
fcd333275b3006dbcbe3ee5ecec47869fb06664b8d56e0e9cf6b58976b186ff3	PlayStation Redump Supplement/Planet Laika (J) T+Eng v1.2 Cargodin/Planet Laika (J) T+Eng v1.2 Cargodin.cue	836968f7d6ce5006cf059c907b22ec54ee783ecb	2c2fcf9ed35f365d2af9f5da15fffeed	e175d239
```

did you convert the redump cue/bin to ISO? I just drag dropped the redump BIN over the batch and came up with a different result for some reason.

The batch file has a way of handling .bin files so not sure if that actually meaningfully changes the data (or just the subchannel data being different between ISO and BIN being the root cause).

**Comment by tjanas** [comment]
I ran the included batch script against my redump bin/cue

**Comment by birdybro** [comment]
Welp, I don't know what happened but somehow we got different numbers. :P

**Comment by tjanas** [comment]
I think I see the problem; when I applied the patch, it was version 1.2. It was updated to version 1.3 within the past day. :)

**Comment by tjanas** [comment]
image

**Comment by birdybro** [comment]
Ah! Super weird! :D

**Comment by frederic-mahe** [comment]
@tjanas and @birdybro your work on the SMDB files is much appreciated, many thanks!

**Pull request merged**
