### PR TITLE
NES: Update NES 2.0 headers from 2021-12-25 DB.

### PR DESCRIPTION
**Pull request by hotelvictorcharlie**
Several games in the NES 2.0 SMDB had their headers updated recently. See #730.

### CODE REVIEW

**Comment by tjanas** [comment]
Since this XML is still in flux with lots of changes from the last official 2020-09-27 update, I would like to wait for a bit before making the update.

From an initial inspection, it appears that Gauntlet now uses the correct mapper of 4 instead of 206 (the legacy Nt Mini SMDB had already been using the corrected mapper 4 since it didn't work with the incorrect mapper 206 that designated in the XML until now).

These are the header changes based on the 2021-12-18 update:
```
Updating header for SHA1:FB50E8C5E655DDCC207A96D083CFCB472DF0DEF4 File: Donkey Kong - Original Edition (USA) (Virtual Console).nes
4e 45 53 1a 02 04 30 08 10 00 00 00 02 00 00 01 (old)
4e 45 53 1a 02 04 30 08 20 00 00 00 02 00 00 01 (new)

Updating header for SHA1:3BD76AF54A9A2760E5AF975BEEA877057F08E871 File: Gauntlet (USA).nes
Updating incorrect mapper from 206 to 4.
4e 45 53 1a 08 08 e8 c8 00 00 00 00 00 00 00 01 (old)
4e 45 53 1a 08 08 48 08 00 00 00 00 00 00 00 01 (new)

Updating header for SHA1:D456FBFFDF41BBBA327D16CD1D776A6BDEDDB586 File: Lode Runner (USA).nes
4e 45 53 1a 01 01 01 08 00 00 00 00 00 00 00 23 (old)
4e 45 53 1a 01 01 01 08 00 00 00 00 00 00 00 20 (new)

Updating header for SHA1:C835985E31C1194073F5A843419F220D41C8AAFA File: Track & Field II (USA) (Rev 1).nes
4e 45 53 1a 08 10 10 08 00 00 00 00 00 00 00 08 (old)
4e 45 53 1a 08 10 10 08 00 00 00 00 00 00 00 01 (new)

Updating header for SHA1:E13626A09AD745BC5D9FB0972383DBF358DEADDC File: Battletoads (Europe).nes
4e 45 53 1a 10 00 70 08 00 00 00 07 01 00 00 01 (old)
4e 45 53 1a 10 00 70 08 20 00 00 07 01 00 00 01 (new)

Updating header for SHA1:A017A0A0AEE71FEA7BCFCB5D889E710516AB330C File: Donkey Kong - Original Edition (Europe) (Virtual Console) (NTSC).nes
4e 45 53 1a 02 04 30 08 10 00 00 00 02 00 00 01 (old)
4e 45 53 1a 02 04 30 08 20 00 00 00 02 00 00 01 (new)

Updating header for SHA1:A16F303BAA02EAAED3215FD4123BA09D32481774 File: Track & Field II (Europe).nes
4e 45 53 1a 08 10 10 08 00 00 00 00 01 00 00 08 (old)
4e 45 53 1a 08 10 10 08 00 00 00 00 01 00 00 01 (new)

Updating header for SHA1:7708275B2C36B180D252FC9528843D89753BCA1F File: Family Trainer 4 - Jogging Race (Japan).nes
Updating incorrect mapper from 70 to 3.
4e 45 53 1a 02 10 61 48 00 00 00 00 00 00 00 0d (old)
4e 45 53 1a 02 10 31 08 20 00 00 00 00 00 00 0d (new)

Updating header for SHA1:D477320DC99B294B5D26995F1527ECA0233F2F46 File: Gorilla Man, The (Japan).nes
4e 45 53 1a 20 00 40 08 00 00 00 07 00 00 00 01 (old)
4e 45 53 1a 20 00 40 08 00 00 00 07 00 00 00 16 (new)

Updating header for SHA1:9C1DF13CEC60CDED981E5F6D4F8E9486CB2F31C1 File: J.League Fighting Soccer - The King of Ace Strikers (Japan).nes
4e 45 53 1a 08 10 42 08 00 00 70 00 00 00 00 01 (old)
4e 45 53 1a 08 10 42 08 00 00 70 00 00 00 00 22 (new)

Updating header for SHA1:127B2C71AB249ECC197F7F88CEFC1FDE2EC7F2CE File: Jetsons, The - Cogswell's Caper (Japan).nes
4e 45 53 1a 08 20 00 38 00 00 00 00 00 00 00 01 (old)
4e 45 53 1a 08 20 00 38 10 00 00 00 00 00 00 01 (new)

Updating header for SHA1:61D0B87E5F0C6723BA203370DCF317F8FBAE7F0B File: Kyuukyoku Tiger (Japan).nes
4e 45 53 1a 08 10 42 08 00 00 70 00 00 00 00 01 (old)
4e 45 53 1a 08 10 40 08 00 00 00 00 00 00 00 01 (new)

Updating header for SHA1:0FE282955F5CA4BEB8E4D1755C2FF110E31DC921 File: Nekketsu! Street Basket - Ganbare Dunk Heroes (Japan).nes
4e 45 53 1a 08 10 40 08 00 00 00 00 00 00 00 01 (old)
4e 45 53 1a 08 10 40 08 00 00 00 00 00 00 00 03 (new)

Updating header for SHA1:E5F893A247FEE3FA24E5D32129AEC53F07304CBB File: Parodius Da! (Japan).nes
4e 45 53 1a 08 10 70 18 20 00 07 00 00 00 00 01 (old)
4e 45 53 1a 08 10 70 18 20 00 05 00 00 00 00 01 (new)

Updating header for SHA1:6D528E12F8EC36C747C0E18311B812D83972DBB2 File: Seiryaku Simulation - Inbou no Wakusei - Shancara (Japan).nes
4e 45 53 1a 08 10 42 08 00 00 70 00 00 00 00 01 (old)
4e 45 53 1a 08 10 42 08 00 00 70 00 00 00 00 22 (new)

Updating header for SHA1:9D22023F55E608687776B53E27E016BB5F81CAA6 File: Tanigawa Kouji no Shougi Shinan III (Japan).nes
4e 45 53 1a 08 00 10 08 00 00 00 07 00 00 00 01 (old)
4e 45 53 1a 08 00 12 08 00 00 70 07 00 00 00 01 (new)

Updating header for SHA1:1B90E37458037C8F23F71FA4B45E54CC53A05139 File: Zenbei Pro Basket (Japan).nes
4e 45 53 1a 08 10 12 08 00 00 70 00 00 00 00 01 (old)
4e 45 53 1a 08 10 10 08 00 00 00 00 00 00 00 01 (new)

Updating header for SHA1:CBC32F60E8780E27645FC9DE4446CE92F2D5E636 File: Pirates! (Germany).nes
4e 45 53 1a 08 10 10 08 00 00 00 00 01 00 00 01 (old)
4e 45 53 1a 08 10 12 08 00 00 70 00 01 00 00 01 (new)

Updating header for SHA1:4B0C6B9580F3107BF50B7B7E7B345573DE6E6597 File: Di Guo Feng Bao - Napoleon's War (Unl) [f1].nes
4e 45 53 1a 10 20 02 b8 00 00 90 07 03 00 00 01 (old)
4e 45 53 1a 10 20 02 b8 20 00 90 00 03 00 00 01 (new)

Updating header for SHA1:6B19F9D888491FB12E1A28883BC275E11D2BA6F2 File: M&M Heroes (Unl) [f1].nes
4e 45 53 1a 10 20 02 b8 00 00 90 00 03 00 00 01 (old)
4e 45 53 1a 10 20 02 b8 20 00 90 00 03 00 00 01 (new)

Updating header for SHA1:2FA7C0E60634C12EF54D857BF7AF45D4971066FE File: Po Fu Chen Zhou (ES-1092) (Ch) (Decrypted).nes
4e 45 53 1a 20 00 02 b8 00 00 90 07 03 00 00 01 (old)
4e 45 53 1a 20 00 02 b8 20 00 90 07 03 00 00 01 (new)

Updating header for SHA1:7235F3F8F0CA37B7C1EE6923A6DA272C08E0C817 File: Romance of The Three Kingdoms - Domineer The World - Xiong Ba Tian Xia (Unl).nes
4e 45 53 1a 20 00 02 b8 00 00 90 07 03 00 00 01 (old)
4e 45 53 1a 20 00 02 b8 20 00 90 07 03 00 00 01 (new)

Updating header for SHA1:54953CB9244E8CB415E0F94E35376790AD685CC8 File: Venice Beach Volleyball (Asia) (En) (Super Mega) (Unl).nes
Updating incorrect mapper from 3 to 172.
4e 45 53 1a 02 04 31 08 10 00 00 00 00 00 00 01 (old)
4e 45 53 1a 02 04 c1 a8 00 00 00 00 00 00 00 01 (new)

Updating header for SHA1:047EFBAA55E4C806EDCCC428EF824306DCED17C4 File: Xiong Ba Tian Xia (Ch) (Wxn).nes
4e 45 53 1a 20 00 02 b8 00 00 90 07 03 00 00 01 (old)
4e 45 53 1a 20 00 02 b8 20 00 90 07 03 00 00 01 (new)

Updating header for SHA1:87E7943769CE95747AC80DA044B2CF9E63410AF2 File: Track & Field II (USA).nes
4e 45 53 1a 08 10 10 08 00 00 00 00 00 00 00 08 (old)
4e 45 53 1a 08 10 10 08 00 00 00 00 00 00 00 01 (new)

Updating header for SHA1:E285527F842A1319701F1BC1E2ED1630F8E5FE63 File: Nintendo - NTF2 System Cartridge (USA).nes
4e 45 53 1a 02 08 10 08 00 00 00 00 00 00 00 2a (old)
4e 45 53 1a 02 08 12 08 00 00 70 00 00 00 00 2a (new)
```

**Comment by hotelvictorcharlie** [comment]
The NES 2.0 DB has been unchanged for over a month now, so it might be time to consider merging this.

**Comment by tjanas** [comment]
You are correct, I will review this soon.

**Comment by tjanas** [comment]
This will be resolved via https://github.com/frederic-mahe/Hardware-Target-Game-Database/pull/768

**Pull request closed without merging**
