### PR TITLE
Sms update

### PR DESCRIPTION
**Pull request by birdybro**
The following changes were made in this major update.

1. Moved Genesis Controller hacks to the appropriate hacks subfolder. These hacks can cause problems on original hardware and in accurate emulators, and given that they are hacks they shouldn't be in the main region folders.
2. Removed the "Everdrive Fixed" entries where they appeared in regular region folders and moved them to the hacks folder.
3. Removed redundant entries between regions to the best of my abilities. e.g. --> There doesn't need to be an Astro Warrior in both the Japanese and US region folders, and it has Japan first in the region summary of the title, so I kept it only in Japan.
4. The alphabetical order has been fixed. I did a parse of the whole set to fix this.
5. Added a missing BIOS file from No-Intro.
6. Added some revisions that were missing, including Sega Ages revisions.
7. Renamed an erroneously named entry ("Super Wonder Boy ~ Wonder Boy (Japan, Europe.sms) --> Wonder Boy (Japan, Europe).sms). Super Wonder Boy was only used in Japan for Super Wonder Boy - Monster World (which is actually Wonder Boy in Monster Land everywhere else -_-;...)
8. Added all of the missing unlicensed ROMs (there were a lot).
9. Renamed Sky Jaguar as the region was incorrectly placed.
10. Added missing betas/prototypes.
11. Removed a redundant revision that is already the primary revision in the Europe folder.

Updated the following translations:

* http://www.romhacking.net/translations/1069/ (updated phantasy star translation to v2.2)

Added the following translations:

* http://www.romhacking.net/translations/6429/ (addendum to the phantasy star patch above that changes names to a different type)
* http://www.romhacking.net/translations/5759/ (Added this patch onto the other translation patch with both variants of the patch, it translates the title screen and has an alternate title screen as well)
* http://www.romhacking.net/translations/5648/

Added the following hacks and combos to hacks where compatible:

* http://www.romhacking.net/hacks/6299/
* http://www.romhacking.net/hacks/4823/
* http://www.romhacking.net/hacks/5248/
* http://www.romhacking.net/hacks/6273/
* http://www.romhacking.net/hacks/5989/
* http://www.romhacking.net/hacks/5990/
* http://www.romhacking.net/hacks/6011/
* http://www.romhacking.net/hacks/4873/
* http://www.romhacking.net/hacks/6369/

Please take your time checking my work, it's a big one. If there are any changes that need to be made, please let me know.

After this update I plan on running the current version of the script to add the file sizes to the file, as it required using an outdated version of the script to update this. I wanted to do them separate that way the git blame history of this update is retained in some way.

### CODE REVIEW

**Comment by tjanas** [comment]
@birdybro thank you for this well-documented PR, and for keeping file sizes out of these commits. I will review.

**Comment by tjanas** [comment]
Can you keep `Astro Warrior (Japan, USA, Brazil)` in the US directory only? That is the convention when one of its regions is USA. If a rom is Japan plus other regions not USA, then it goes in Japan.

**Comment by tjanas** [comment]
The following was renamed to no longer match its no-intro name, could you change it back?
`World Cup USA 94 (Europe, Brazil) (En,Fr,De,Es,It,Nl,Pt,Sv).sms`
`https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0431

**Comment by tjanas** [comment]
The following entry was added and should be removed:
```
52de4e29f973f12cf5184447a2c8dd802152ef42a3b82935bfc55fa52ae313cd Master EverDrive/2 Japan - A-Z/Great Ice Hockey (Japan, USA).sms bbe6bd6b59e5ae20cd1a4a8c72276aac7d2964a3 374d762b51b1c5ea8ff7903f98586e0e 0cb7e21f
```
According to no-intro, this is a bad dump (the good dump with crc32 946b8c4a already exists in its correct US directory).

**Comment by tjanas** [comment]
This looks to be in the wrong directory (should be in Europe):
```
Master EverDrive/1 US - A-Z/World Cup USA 94 (Europe, Brazil) (En,Fr,De,Es,It,Nl,Pt,Sv).sms
```

**Comment by tjanas** [comment]
Rename `Asterix and the Great Rescue (Europe, Brazil)` back to its [no-intro](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0038) name of `Asterix and the Great Rescue (Europe, Brazil) (En,Fr,De,Es,It)`

**Comment by tjanas** [comment]
Please remove `Master EverDrive/2 Japan - A-Z/Astro Warrior (Japan, USA, Brazil).sms` since it exists in the US directory per https://github.com/frederic-mahe/Hardware-Target-Game-Database/pull/775/commits/cedcd73bb81168b80d65597dc15870d37414bb1c

**Comment by tjanas** [comment]
Please rename
`Master EverDrive/2 Japan - A-Z/Wonder Boy (Japan, Europe).sms`
to
`Master EverDrive/2 Japan - A-Z/Wonder Boy (Japan, Europe) (En).sms`
per [no-intro](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0380)

**Comment by tjanas** [comment]
Please rename `94-Nen Super Basketball (Taiwan) (Unl).sms` to `94-Nen Super Basketball (Taiwan) (En) (Unl).sms` per [no-intro](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0639)

**Comment by tjanas** [comment]
Please rename `Action Boy (Taiwan) (Unl).sms` to `Action Boy (Taiwan) (En) (Unl).sms` per [no-intro](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0643)

**Comment by tjanas** [comment]
Please rename `Aerial Assault (Taiwan) (Unl).sms`  to `Aerial Assault (Taiwan) (En) (Unl).sms` per [no-intro](https://datomatic.no-intro.org/index.php?page=show_record&s=26&n=0631)

**Comment by tjanas** [comment]
`Alocos (Taiwan) (Unl).sms` -> `Alocos (Taiwan) (En) (Unl).sms`
`Astro Adventure (Taiwan) (Unl).sms` -> `Astro Adventure (Taiwan) (En) (Unl).sms`
`Black Belt (Taiwan) (Unl).sms` -> `Black Belt (Taiwan) (En) (Unl).sms`
`Bubble Bobble (Taiwan) (Unl).sms` -> `Bubble Bobble (Taiwan) (En) (Unl).sms`
`Cyber Shinobi, The (Taiwan) (Unl).sms` -> `Cyber Shinobi, The (Taiwan) (En) (Unl).sms`
`Double Dragon (Taiwan) (Unl).sms` -> `Double Dragon (Taiwan) (En) (Unl).sms`
`Forgotten Worlds (Taiwan) (Unl).sms` -> `Forgotten Worlds (Taiwan) (En) (Unl).sms`
`Kung Fu Kid (Taiwan) (Unl).sms` -> `Kung Fu Kid (Taiwan) (En) (Unl).sms`
`Lord of Sword (Taiwan) (Unl).sms` -> `Lord of Sword (Taiwan) (Ja) (Unl).sms`
`Northen Ken (Taiwan) (Unl).sms` -> `Northen Ken (Taiwan) (Ja) (Unl).sms`
`Paper Boy (Taiwan) (Unl).sms` -> `Paper Boy (Taiwan) (En) (Unl).sms`
`Prince of Persia (Taiwan) (Unl).sms` -> `Prince of Persia (Taiwan) (En) (Unl).sms`
`Quartet (Taiwan) (Unl).sms` -> `Quartet (Taiwan) (En) (Unl).sms`
`R-Type (Taiwan) (Unl).sms` -> `R-Type (Taiwan) (En) (Unl).sms`
`Scramble Spirits (Taiwan) (Unl).sms` -> `Scramble Spirits (Taiwan) (En) (Unl).sms`
`Shadow Dancer (Taiwan) (Unl).sms` -> `Shadow Dancer (Taiwan) (En) (Unl).sms`
`Shadow of the Beast (Taiwan) (Unl).sms` -> `Shadow of the Beast (Taiwan) (En) (Unl).sms`
`Shangwei Mingling (Taiwan) (Unl).sms` -> `Shangwei Mingling (Taiwan) (En) (Unl).sms`
`Sky Jaguar (Clover) (Korea) (Unl).sms` -> `Sky Jaguar (Korea) (Clover) (Unl).sms`
`Strider, The (Taiwan) (Unl).sms` -> `Strider, The (Taiwan) (En) (Unl).sms`
`Submarine Attack (Taiwan) (Unl).sms` -> `Submarine Attack (Taiwan) (En) (Unl).sms`
`Thunder Blade (Taiwan) (Unl).sms` -> `Thunder Blade (Taiwan) (En) (Unl).sms`

**Comment by tjanas** [comment]
Please put the following placeholder entry back:
```
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 Master EverDrive/3 Sega SG-1000/@Place Sega SG-1000 Pack Here da39a3ee5e6b4b0d3255bfef95601890afd80709 d41d8cd98f00b204e9800998ecf8427e 00000000
```

**Comment by tjanas** [comment]
The following entry was correctly added to Betas according to no-intro dat:
```
0bf7700ea91f0a1dfc8145b5d330cb87b02573264937022b9ababbf31bce2360 Master EverDrive/4 Betas, Prototypes, Revisions/Betas/3D Gunner (USA) (Beta).sms 2f66b626416902a4b0a81c682c9c40579f32e7be 486dea48606666b44c7e6db9d7a1454c 56dcb2d4
```
but the following should be removed from Samples since it is the same file:
```
0bf7700ea91f0a1dfc8145b5d330cb87b02573264937022b9ababbf31bce2360 Master EverDrive/4 Betas, Prototypes, Revisions/Samples/3D Gunner (USA) (Demo).sms 2f66b626416902a4b0a81c682c9c40579f32e7be 486dea48606666b44c7e6db9d7a1454c 56dcb2d4
```

**Comment by birdybro** [comment]
Thanks for taking a look! I will fix those later tonight!

**Comment by tjanas** [comment]
`Basketball Nightmare (Europe, Brazil) (Beta).sms` -> `Basketball Nightmare (Europe, Brazil) (En) (Beta).sms`
`Battle Wings (World) (Beta).sms` -> `Battle Wings (World) (Beta) (1988-09-07).sms`
`Dead Angle (USA, Europe, Brazil) (Beta).sms` -> `Dead Angle (USA, Europe, Brazil) (En) (Beta).sms`
`Heroes of the Lance (Europe, Brazil) (Beta).sms` -> `Heroes of the Lance (Europe, Brazil) (En) (Beta).sms`
`OutRun 3-D (Europe, Brazil) (Beta).sms` -> `OutRun 3-D (Europe, Brazil) (En) (Beta).sms`
`Rastan (USA, Europe, Brazil) (Beta).sms` -> `Rastan (USA, Europe, Brazil) (En) (Beta).sms`
`Thunder Blade (USA, Europe, Brazil) (Beta).sms` -> `Thunder Blade (USA, Europe, Brazil) (En) (Beta).sms`
`Color & Switch Test (Japan) (Proto).sms` -> `Color & Switch Test (Japan) (En) (Proto).sms`

**Comment by tjanas** [comment]
Remove this old translation: `Phantasy Star (J) T+Eng v2.00 SMS Power!.sms`
since `Phantasy Star (J) T+Eng v2.2 SMS Power!.sms` replaces it.

**Comment by tjanas** [comment]
...I think that's everything. :)

**Comment by birdybro** [comment]
I think I did it all now.

**Comment by tjanas** [comment]
`Master EverDrive/2 US - A-Z/Astro Warrior (Japan, USA, Brazil).sms`

I think it’s supposed to be “1 US - A-Z”

**Comment by birdybro** [comment]
Fixed

**Comment by frederic-mahe** [comment]
awesome work from both of you @birdybro and @tjanas, thank you!

**Comment by tjanas** [comment]
Could you remove the following entry? It’s already reflected in the tools & service test carts directory:

`Master EverDrive/4 Betas, Prototypes, Revisions/Prototypes/Color & Switch Test (Japan) (En) (Proto).sms`

**Comment by tjanas** [comment]
I am going to merge this pull request and will take care of the following in a future commit...
Remove these two entries as they are already reflected in the tools & service test carts directory:
```
Master EverDrive/4 Betas, Prototypes, Revisions/Prototypes/Color & Switch Test (Japan) (En) (Proto).sms
Master EverDrive/4 Betas, Prototypes, Revisions/Prototypes/Sega Graphic Board (USA) (v2.0) (Proto).sms
```
Add the following no-intro entries:
```
rom name="Alex Kidd in Miracle World (World) (Ja) (Sega Ages).sms" size="131072" crc="6f5f3daa" md5="bd8016f2dccd89de716918da79359ff6" sha1="c68a2832d8578b24b1e0820f30b554aeea828ece" status="verified"
rom name="Phantasy Star (World) (Ja) (Sega Ages).sms" size="565248" crc="df96f194" md5="1777bf6df3331e2391835ed62a037de8" sha1="c5f19946b5f157d767b3a5a7b95e8463a1bfaaae"
rom name="Zillion II - The Tri Formation (World) (Beta).sms" size="131072" crc="5b1cf392" md5="281eb7a9dfabe6ca444398a295440ed2" sha1="fdc156deffd5ff4f57b88dfe18dbd45560cb433f"
```

**Comment by hotelvictorcharlie** [comment]
@birdybro Thank you for this large update! What is the checksum of the source rom you used for these 2 hacks?
```
Master EverDrive/4 Hacks/Voyage - A Sorceress' Vacation (Alex Kidd in Miracle World Hack) (1.05) SNAGS.sms
Master EverDrive/4 Hacks/Voyage - A Sorceress' Vacation - Catalan Version (Alex Kidd in Miracle World Hack) (1.03) SNAGS.sms
```
The reason I ask is because the old version (1.03) used `aed9aac4` (which is the one listed on [romhacking](https://www.romhacking.net/hacks/4873/)), but when I apply the 1.05 patches to that same original rom, the resulting checksum doesn't match yours.

But I'm confused because romhacking says *not* to use the Brazillian rom, and then lists the checksum of the Brazillian rom. 🙃 

Also, can we remove the old (English) 1.03 version from the SMDB now that we have 1.05?

**Pull request merged**
