### PR TITLE
Add file size to SMDB files on parse

### PR DESCRIPTION
**Pull request by coughlanio**
_Opening PR again as the previous one was closed_

Proposing adding the file size to SMDBs. This can be used for additional verification, and particularly, when converting SMDB to another DAT format for use in a ROM tool like ROMVault, via SabreTools.

Parse, build & verify have been tested to ensure no regressions have been introduced.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
hi @coughlanio I am ok with the idea of extending SMDBs with a file size column, especially if doing so improves compatibility with other databases.

As of now, `build_pack.py` and `verify_pack.py` ignore additional columns so there is nothing to change there.

Could you please check if using `os.path.getsize(file)` gives you similar results? If yes, I'd prefer using that rather than `f.tell()`

Also, I think file size should be computed on both branches of the `try...except`, not just on the first branch.

**Comment by coughlanio** [comment]
@frederic-mahe My immediate thought is that doing `os.path.getsize()` would impact performance, but I can do some testing/benchmarking to compare. What is your issue with `f.tell()`?

**Comment by frederic-mahe** [comment]
I had to look at the documentation for `f.tell()` whereas what `getsize()` does is more obvious (in my opinion). "Semantically clearer", if that's a thing??

**Comment by coughlanio** [comment]
@frederic-mahe That's a fair point, I'd say if it doesn't have massive performance impact, it's a good option. I'm going to do some benchmarking on one of the CD packs now, will let you know how it goes.

**Comment by coughlanio** [comment]
@frederic-mahe looks like it's within a margin of error between both options. I also benchmarked the script without the addition of size, and not seeing a meaningful difference.

|Function|Pack|Time|
|---|---|---|
|f.tell()|Project Peacock|1:53.92|
|os.path.getsize()|Project Peacock|1:53.96|
|master|Project Peackock|1:53.87|
|f.tell()|C64|27.703|
|os.path.getsize()|C64|27.540|
|master|C64|27.961|

**Comment by coughlanio** [comment]
I've changed this PR to use `os.path.getsize()`.

> Also, I think file size should be computed on both branches of the try...except, not just on the first branch.

I think I had already covered this? Unless I'm missing something!

**Comment by frederic-mahe** [comment]
Thanks @coughlanio !

**Pull request merged**
