### PR TITLE
Update MiSTer Amiga pack

### PR DESCRIPTION
**Pull request by coughlanio**
Updating Amiga pack to reflect the contents of the `2021-03-13` release.

### CODE REVIEW

**Comment by frederic-mahe** [comment]
Hi @coughlanio could you please give more details on what has been updated?

As a side note, now that there is a new column in SMDB files, I suggest to separate commits adding file sizes, and commits with other modifications to the SMDB entries in future pull requests. It will make the review process easier.

**Comment by coughlanio** [comment]
I suspect because this pack hasn't been updated in a long time, the source files have been lost to time, so it makes it difficult to update the existing pack with just the size added.

I updated this pack by parsing the latest files I could find, which was the `2021-03-13` release. Perhaps @tjanas might have access to the original source files?

**Comment by tjanas** [comment]
Can you use the older version of the parse script so that it doesn’t add the file size? Like @frederic-mahe mentioned, it will be easier to see differences.

What are the sources of these Amiga files? TOSEC? I have no familiarity with Amiga.

**Comment by tjanas** [comment]
I see there are config files included which don’t seem appropriate for a HTGDB, since they are likely plain text without a deterministic hash.

**Comment by coughlanio** [comment]
> Can you use the older version of the parse script so that it doesn’t add the file size? Like @frederic-mahe mentioned, it will be easier to see differences.

Can take a look at doing this.

> What are the sources of these Amiga files? TOSEC? I have no familiarity with Amiga.

HTGDB Gamepacks on Archive.org

**Comment by coughlanio** [comment]
@frederic-mahe @tjanas I've pushed the changes as two separate commits. More than happy to discuss the implications of config files being included in the pack.

**Comment by tjanas** [comment]
I would rather it be two separate pull requests, the first pull request not including the new filesize field. Also, there should not be config files and other non-deterministic files included (they should be made freely available elsewhere on a mister-specific github). Perhaps this pull request should be closed and start with a new one.

**Comment by frederic-mahe** [comment]
MiSTer SMDBs are a bit special, with a lot of MiSTer-specific config files and "black-boxes" (e.g.; hard-drive images). In other SMDBs, we've discarded flashcart specific files, we should do the same with MiSTer files, @tjanas is right. Sorry you have to go through so many hoops @coughlanio

**Comment by coughlanio** [comment]
No worries, the context is useful. 

> MiSTer SMDBs are a bit special, with a lot of MiSTer-specific config files and "black-boxes" (e.g.; hard-drive images). In other SMDBs, we've discarded flashcart specific files, we should do the same with MiSTer files, @tjanas is right. Sorry you have to go through so many hoops @coughlanio

Got it, are you proposing we remove things like hard drive images? For stuff like Amiga, that's the bread and butter so I see value in them existing.

**Comment by dukrous** [comment]
VHDs are also how ao486 works. If HTGDB is meant to be hardware agnostic, maybe the MiSTer packs should be spun off into a different project?

**Comment by frederic-mahe** [comment]
> Are you proposing we remove things like hard drive images? For stuff like Amiga, that's the bread and butter so I see value in them existing.

What I meant is that SMDB files were initially designed to organize loose collections of ROM files, not monolithic archives. I perfectly understand that, at least for now, VHD and hard drive images are an easier and much appreciated solution for some MiSTer cores, and I don't suggest we remove them.

The situation might be different for config files and other MiSTer-specific files that come with the VHDs. Our experience with this kind of companion files is that they make it harder to build 100% complete packs. I have no idea if this is the case with the Amiga set, so I let you judge.

**Comment by tjanas** [comment]
> VHDs are also how ao486 works. If HTGDB is meant to be hardware agnostic, maybe the MiSTer packs should be spun off into a different project?

It's my opinion that the HTGDB is not an appropriate place for containing hashes of VHDs for ao486 and others. I think there is a place for some MiSTer-specific packs where an end-user could ultimately build a complete pack from a known external data source (e.g. nointro, redump, TOSEC, etc). I believe these VHD files are custom made by those in the community; whoever creates and hosts those could also provide the supplemental files (e.g. config files) with them.

**Comment by dukrous** [comment]
> It's my opinion that the HTGDB is not an appropriate place for containing hashes of VHDs for ao486 and others. I think there is a place for some MiSTer-specific packs where an end-user could ultimately build a complete pack from a known external data source (e.g. nointro, redump, TOSEC, etc). I believe these VHD files are custom made by those in the community; whoever creates and hosts those could also provide the supplemental files (e.g. config files) with them.

This has always been the hardest part of building Amiga and ao486 MiSTer packs: you need to find out which specific version of the file is hashed to get a proper build. At least with ao486 the ExoDOS Top 300 pack would be a good inclusion as they're on a publicly accessible Archive link maintained by the creator, but MegaAGS has nothing comparable that I've found and always seemed like someone's well-kept secret.

This makes maintaining proper and up to date hashes very difficult compared to the drop-in quality of the console specific packs.

**Comment by tjanas** [comment]
> This has always been the hardest part of building Amiga and ao486 MiSTer packs: you need to find out which specific version of the file is hashed to get a proper build. At least with ao486 the ExoDOS Top 300 pack would be a good inclusion as they're on a publicly accessible Archive link maintained by the creator

Correct. Perhaps some additional information could be provided on the [MiSTer Amiga](https://github.com/MiSTer-devel/Minimig-AGA_MiSTer) github that could assist end-users, since it has a much higher learning curve and less forgiving than working with flash cart or jailbreak on a console. The creator of that Top 300 pack could/should provide checksum information with it. Even that doesn't really belong here in the HTGDB.

**Comment by coughlanio** [comment]
@frederic-mahe Is there any chance we can get this merged so we can at least have it match the files that are publicly available, and I can spend some time figuring out a better way to manage this going forward?

**Pull request merged**
