### PR TITLE
PSX Redump Supp: fix erroneous ff7 directory structure and naming and add m3u

### PR DESCRIPTION
**Pull request by birdybro**
I added m3u's to my previous one for retroarch and mednafen usability, so same here, and didn't realize how the folder structure originally was setup, so fixed that too.

### CODE REVIEW

**Comment by tjanas** [comment]
I don’t think m3u should be added here since those are for emulators and doesn’t target hardware solutions like PSIO, XStation, MODE, etc

**Comment by birdybro** [comment]
Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font vR06g GreenGoblin) (Disc 1).cue  
```
FILE "Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font vR06g GreenGoblin) (Disc 1).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

```

Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font vR06g GreenGoblin) (Disc 2).cue  
```
FILE "Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font vR06g GreenGoblin) (Disc 2).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

```

Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font vR06g GreenGoblin) (Disc 3).cue  
```
FILE "Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font vR06g GreenGoblin) (Disc 3).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

```

Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font, HardType vR06g GreenGoblin) (Disc 1).cue  
```
FILE "Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font, HardType vR06g GreenGoblin) (Disc 1).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

```

Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font, HardType vR06g GreenGoblin) (Disc 2).cue  
```
FILE "Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font, HardType vR06g GreenGoblin) (Disc 2).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

```

Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font, HardType vR06g GreenGoblin) (Disc 3).cue  
```
FILE "Final Fantasy VII (USA) (Retranslation, Canon, Chicago Font, HardType vR06g GreenGoblin) (Disc 3).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00

```

**Comment by tjanas** [comment]
@birdybro check the case on your directory name, should be "PlayStation" and not "Playstation":
`Playstation Redump Supplement/Final Fantasy VII Retranslation (U) T+Eng vR60g GreenGoblin`

**Comment by birdybro** [comment]
Done, another newbie mistake! :P

**Pull request merged**
