### PR TITLE
N64: no-intro update (20220911-034608)

### PR DESCRIPTION
**Pull request by tjanas**
Replaces known bad dumps of Charlie Blast's Territory (USA), Donald Duck - Goin' Quackers (USA), Robotron 64 (USA), Donald Duck - Quack Attack (Europe), Bomberman 64 (Japan), Parlor! Pro 64 - Pachinko Jikki Simulation Game (Japan), Rally '99 (Japan), Duck Dodgers Starring Daffy Duck (USA) (En,Fr,Es) (Beta), Glover 2 (USA) (Proto 1), Glover 2 (USA) (Proto 2), Legend of Zelda, The - Ocarina of Time - Master Quest (Europe) (Debug) (GameCube).

Remove Chinese iQue entries.

Remove bad dump of Derby Stallion 64 (Japan) (Beta), Glover (USA) (Beta) (1998-07-16), Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-06-06), Turok 3 - Shadow of Oblivion (Europe) (Beta) (2000-07-10).

Remove Banjo-Kazooie (U) EverDrive Patched, Banjo-Tooie (U) EverDrive Patched, Jet Force Gemini (U) EverDrive Patched (I can find no mention of them on krikzz forum or romhacking.net or anywhere else, they might have been from before EverDrive 64 firmware bug fixes).

Add new betas, prototypes, service test carts from no-intro.
[Nintendo - Nintendo 64 (BigEndian) (20220911-034608).zip](https://github.com/frederic-mahe/Hardware-Target-Game-Database/files/9548540/Nintendo.-.Nintendo.64.BigEndian.20220911-034608.zip)

### CODE REVIEW

**Comment by EloraDarling** [comment]
The EverDrive Patched files were to remove the CEC lockout chip requirements for them since they use oddball lockout chips, which won't work for EverDrive users that don't have an UltraCIC chip with the ability to support them. That's why I had them in there. Sorry for being away from this for so long.

**Comment by Drakonas** [comment]
@tjanas Please delete that message. I was using the wrong account

The EverDrive Patched files were to remove the CEC lockout chip requirements for them since they use oddball lockout chips, which won't work for EverDrive users that don't have an UltraCIC chip with the ability to support them. That's why I had them in there. Sorry for being away from this for so long.

I don't know if people would have problems with this, but I guess it's fine at this point. I think newer EverDrives don't care.

I cannot provide them as they've long been in the SMDB before I ever touched the project.

**Comment by Drakonas** [comment]
I really don't know what cartridges are still affected, but there may be a few people still using older Everdrives without UltraCIC. This is where it's troublesome and the patches were needed. People that have Everdrive 64 v2's, for example, would not have the option to play the RARE games, since they used a different CIC chip than most other N64 titles.

**Comment by Drakonas** [comment]
I should mention that finding the patches is probably impossible. My guess is they were released in rom form. Looking through some old forums from 2012, it seems they were posted on the old Assembler Games Everdrive forums, which I believe is basically the original home for Everdrive forums, but is now shut down since 2018-2019.

I don't want to link to it because they contain cracked roms, but you can find the information by searching Google (for informational purposes only obviously).

**Pull request merged**
