### PR TITLE
EverDrive 64: Add 5 old-new LOZ Ocarina of Time Hacks

### PR DESCRIPTION
**Pull request by birdybro**
Just confirmed to work on original hardware w/ EverDrive x7 thanks to PaisleyBoxer. The Nightmare hack unfortunately does not currently work on original hardware even though it was properly patched as per instructions. May need an adjustment to the size of the ROM as it doesn't match and the error was that it was too large (17KB larger than typical z64 files).

http://www.romhacking.net/news/2507/ - Main News Article for re-release of these hacks

http://www.romhacking.net/hacks/5797/ - The Legend of Zelda: Voyager of Time

http://www.romhacking.net/hacks/5810/ - Nimpize Adventure

http://www.romhacking.net/hacks/5816/ - Zelda 64: Dawn & Dusk

http://www.romhacking.net/hacks/5811/ - The Fate of the Bombiwa

http://www.romhacking.net/hacks/5801/ - The Legend of Zelda: Master of Time

### CODE REVIEW

**Comment by tjanas** [comment]
Can you confirm these are in big endian format?

**Comment by tjanas** [comment]
I want to be sure these checksums are for files in big endian format, as an effort was recently completed to standardize to big endian (see https://github.com/frederic-mahe/Hardware-Target-Game-Database/issues/199)

**Comment by frederic-mahe** [comment]
I though about endianness, but I wasn't sure it would also apply to hacks.

**Comment by tjanas** [comment]
I checked all of these and can confirm they are BigEndian. All good. The romhacking pages themselves are incorrect as they list "Patching Information" as "Byte Swapped".

**Comment by frederic-mahe** [comment]
Thanks @tjanas !

**Comment by Drakonas** [comment]
Which patch did you use for Zelda 64: Dawn & Dusk? @birdybro

**Comment by Drakonas** [comment]
FYI, the official readme for The Fate of the Bombiwa is actually written by the author, and has 1.0.3 as the version, not 1.03. I'll add this to my notes to be added in a future commit unless you want to take care of it, but we definitely want to be accurate to the original author's version scheme.

**Comment by tjanas** [comment]
> Which patch did you use for Zelda 64: Dawn & Dusk? @birdybro Dawn & Dusk comes with 6 different patches for the 3 revisions from Japan and USA.

I think it was the original USA release: https://datomatic.no-intro.org/index.php?page=show_record&s=24&n=0376

**Comment by tjanas** [comment]
> FYI, the official readme for The Fate of the Bombiwa is actually written by the author, and has 1.0.3 as the version, not 1.03. I'll add this to my notes to be added in a future commit unless you want to take care of it, but we definitely want to be accurate to the original author's version scheme.

Fixed https://github.com/frederic-mahe/Hardware-Target-Game-Database/commit/97712c91e71ac6d553a2664d42a0c4595adba8c6

**Comment by Drakonas** [comment]
Thanks @tjanas. Sorry, I've been prepping to move out and have a vacation in a week as well.

**Comment by birdybro** [comment]
Sorry for my missing the replies in here. I'm still getting used to keeping up with notifications on github.

I apologize for not catching the version number that was incorrect. Romhacking keeps leading me astray and I should make more effort determining what the TRUE intended version number is from now on.

**Comment by tjanas** [comment]
Romhacking doesn’t do a great job in displaying version numbers among other things (often times they will list a version as 1.0 or 1.00 when the patch notes list it as just v1)

**Pull request merged**
