### PR TITLE
 32x prototypes and hacks released in 2020/2021.

### PR DESCRIPTION
**Pull request by blinard-BIOINFO**
@tjanas  @frederic-mahe 
For some reason, in my previous PR #720 all digit-only crc32 got parsed and saved as dates integers (python LOCAL issue...).
The present PR is corrected.

This PR reviews and extends the Mega Everdrive SMDB with all 32x prototypes and hacks released in 2020/2021.

- renamed Dysney's Pinocchio 32x prototype
- adds every 32x hacks currently registered in romhacking.com
- adds a sub-directory "Doom 32x Hacks", as many new hacks appeared in 2021 (and this seems to be only the beginning)

- hack names have been homogenized, following names and versions given by original authors in romhacking.com
- all roms tested and working with everdrive X7
- roms regions verified via headers and confirmed on real hardware (modded with region switch)

### CODE REVIEW

**Comment by tjanas** [comment]
@blinard-BIOINFO : This pull request changes an entry from its [current no-intro name](https://datomatic.no-intro.org/index.php?page=show_record&s=17&n=0066) of `Pinocchio (Europe) (Proto) (1995-06-12).32x` to `Disney's Pinocchio 32x (Europe) (Beta) (1995-12-06).32x`; any particular reason why you changed this entry? Generally all entries should adhere to existing no-intro filenames whenever possible.

**Comment by blinard-BIOINFO** [comment]
@tjanas
* I reverted Pinocchio's rom name.
* I used the no-intro (checsum matches) version and reapplied the ips patches. (strangely the rom i used was different from the no-intro version).
+ I added the USA and japan versions of the hack ot the set (there was one ips patch per region in the romhacking.com archive)

Note: following your comment, I verified all 32x roms on which I applied ips or delta patches to apply the hacks, they are all matching the no-intro checksums.

Everything should be correct now.

**Comment by tjanas** [comment]
Can you explain why some hacks were removed? And provide links to patches for all the new hacks?

**Comment by frederic-mahe** [comment]
hi @blinard-BIOINFO 

> For some reason, in my previous PR #720 all digit-only crc32 got parsed and saved as dates integers (python LOCAL issue...).

Is that something that could be fixed in `parse_pack.py`?

> Can you explain why some hacks were removed? And provide links to patches for all the new hacks?

If I understand correctly, all removed hacks are Doom hacks, which are now in a dedicated sub-directory `Doom 32x Hacks`.

Regarding the list of links to patches, what would be the best way to document the changes @tjanas ? A GitHub comment with a tab-separated two-column list?
```
ROM_name    URL to romhacking.com hack
```

**Comment by tjanas** [comment]
Specifically, I see that these two entries were completely removed and not moved (I cannot find their checksums in the file after the proposed changes):

```
a81ddf3084c1f2f1f19b6ba2dfe206449718e22464982ad4df3d7d8a984e840d	Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/Doom 64 32X (Hack) MarphitimusBlackimus.32x
569b3134065881bce9e5d0d4f0fd23f04e7cc93f0395856a32c3b13034151184	Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/Ultimate Doom 1 & 2 (Hack) e-Doctor 2017-09-01.32x
```

**Comment by blinard-BIOINFO** [comment]
@frederic-mahe 

> > For some reason, in my previous PR #720 all digit-only crc32 got parsed and saved as dates integers (python LOCAL issue...).
> 
> Is that something that could be fixed in `parse_pack.py`?

Recently I played with my conda environments and my Unix LOCAL environment variables, which impacted default python behaviour (notably PYTHONIOENCODING env variable).  I just reverted to a default config and the date IO issue disappeared.

This was really not the default behavior of a classic python setup, so probably it's better to not enter into the nightmarish world of LOCALS  in  `parse_pack.py`. Alternatively,` conda env create -f environment.yaml` or `pip env requirements.txt` could be used to ensure anyone launching the scripts have the same environment (after adding these files and instrucitons in the repository). 

But this may be an overkill for these standalone scripts. 
If you think this may still be useful, I can add a new issue related to this subject.

**Comment by blinard-BIOINFO** [comment]
Below is a detailed list of my the changes. Let me know which one you accept or would like that I revert.
As mentionned before, when a hack is renamed it was maily to add region and hack version, as indicated by romhacking.net.

When you have a real 32x without region switch mod, this information is a must have.

All names are relative to the path: Mega EverDrive/3 Sega 32X/4 Homebrew & Hacks/

- 3 entries Were pesent in the DB and checksums are unchanged.
- 1 entry was present but updated to more recent version of the hack => checksum changed
- all other entries are new

| # | Modification  | Hash update | Old name  | New name  | romhacking.net reference  |
|---|---|---|---|---|---|
| 1 | Added  | YES | None  | Pinocchio (Proto) (1995-12-06) - Prototype Fixes (Europe) (Hack) v1.0 Barone.32x  | https://www.romhacking.net/hacks/4368/  |
| 2 | Added  | YES | None  | Pinocchio (Proto) (1995-12-06) - Prototype Fixes (Japan) (Hack) v1.0 Barone.32x  | https://www.romhacking.net/hacks/4368/  |
| 3 | Added  | YES | None  | Pinocchio (Proto) (1995-12-06) - Prototype Fixes (USA) (Hack) v1.0 Barone.32x  | https://www.romhacking.net/hacks/4368/  |
| 4 | Added  | YES | None  | Mortal Kombat II - Ultimate Edition Improvements (Europe, Japan, USA) (Hack) v1.0 Linkuei .32x  | https://www.romhacking.net/hacks/5521/  |
| 5 | Renamed  | NO | Sonic in Chaotix (Knuckles' Chaotix Hack) Revision 2.32x  | Sonic in Chaotix (Japan, USA) (Hack) v1.2 JJFTails.32x  | https://www.romhacking.net/hacks/399/  |
| 6 | Added  | YES | None  | Stellar Assault Region-Free and Restoration Patch (Europe, Japan, USA) (Hack) v1.0 Vague Rant.32x  | https://www.romhacking.net/hacks/5863/  |
| 7 | Added  | YES | None  | Virtua Racing Deluxe - Mirror Mode (Japan) (Hack) v1.0 Elfor.32x  | https://www.romhacking.net/hacks/5571/  |
| 8 | Added  | YES | None  | Virtua Racing Deluxe - Mirror Mode (USA) (Hack) v1.0 Elfor.32x  | https://www.romhacking.net/hacks/5571/  |
| 9 | Added  | YES | None  | Doom 32X Hacks/Cacosweeper Doom (Europe) (Hack) v1.0 Roebloz.32x  | https://www.romhacking.net/hacks/5194/  |
| 10 | Added  | YES | None  | Doom 32X Hacks/Cacosweeper Doom (Japan, USA) (Hack) v1.0 Roebloz.32x  | https://www.romhacking.net/hacks/5194/  |
| 11 | Added  | YES | None  | Doom 32X Hacks/Doom Spinball (USA) (Hack) v1.0 Saxman.32x  | https://www.romhacking.net/hacks/702/  |
| 12 | Added  | NO | None  | Doom 32X Hacks/Doom 2 All Levels Hack Maps (Europe) (Hack) v1.03 e-Doctor.32x  | https://www.romhacking.net/hacks/5449/  |
| 13 | Renamed, Moved   | NO | Doom 24 Level Expansion Addendum NTSC (Hack) v1.1 Saxman & Nuxius.32x  | Doom 32X Hacks/Doom 32X - 24 Levels expansion + Addendum (Europe) (Hack) v1.1 Saxman & Nuxius .32x  | https://www.romhacking.net/hacks/618/ AND https://www.romhacking.net/hacks/619/ (hack v1.1 corrects hack 1.0, 2 entries, 2 authors, so 2 entries in romhaking.net) |
| 14 | Added  | YES | None  | Doom 32X Hacks/Doom 32X - Delta Edition - Episode 1 (Japan, USA) (Hack) v1.0 Roeblez.32x  | https://www.romhacking.net/hacks/5732/  |
| 15 | Added  | YES | None  | Doom 32X Hacks/Doom 32X - Delta Edition - Episode 2 (Japan, USA) (Hack) v1.0 Roeblez.32x  | https://www.romhacking.net/hacks/5732/  |
| 16 | Added  | YES | None  | Doom 32X Hacks/Doom 32X - Delta Edition - Episode 3 (Japan, USA) (Hack) v1.0 Roeblez.32x  | https://www.romhacking.net/hacks/5732/  |
| 17 | Added  | YES | None  | Doom 32X Hacks/Doom 32X Resurrection (Europe, Japan, USA) (Hack) v1.3 D32XR Team.32x  | https://www.romhacking.net/hacks/6269/  |
| 18 | Added  | YES | None  | Doom 32X Hacks/Doom 32X Thy Flesh Consumed (Japan, USA) (Hack) v1.1 Roeblez.32x  | https://www.romhacking.net/hacks/5376/  |
| 19 | Moved  | NO | Doom 64 32X (Hack) MarphitimusBlackimus.32x  | Doom 32X Hacks/Doom 64 32X (Hack) MarphitimusBlackimus.32x  | no entry in romhacking.net  |
| 20 | Updated hack, Renamed, Moved  | YES | Ultimate Doom 1 & 2 (Hack) e-Doctor 2017-09-01.32x  | Doom 32X Hacks/Ultimate Doom 1 & 2 All Episodes + Addendum (Japan, USA) (Hack) v1.03 e-Doctor.32x  | https://www.romhacking.net/hacks/5446/ (hack version more recent than previous entry) |

**Comment by frederic-mahe** [comment]
Nice work @blinard-BIOINFO

**Comment by frederic-mahe** [comment]
> ...
> This was really not the default behavior of a classic python setup, so probably it's better to not enter into the nightmarish world of LOCALS in `parse_pack.py`. Alternatively,` conda env create -f environment.yaml` or `pip env requirements.txt` could be used to ensure anyone launching the scripts have the same environment (after adding these files and instrucitons in the repository).
> 
> But this may be an overkill for these standalone scripts. If you think this may still be useful, I can add a new issue related to this subject.

Thanks, that won't be necessary. The scripts need a major refactoring, maybe we'll revisit the issue of locals once that'll be done.

**Comment by hotelvictorcharlie** [comment]
Hi @blinard-BIOINFO, thank you for adding these. I have a few questions:

1. For `Doom 2 All Levels Hack Maps (Europe) (Hack) v1.03 e-Doctor.32x`, the only way I can get the listed checksum is by applying the author's NTSC patch to the Japan/USA rom. So should this should say `(Japan, USA)` instead of `(Europe)`? If you apply the Europe patch (or just download [the file that the author posted](https://www.doomworld.com/forum/topic/97985-doom-ii-32x-pc-maps-port/)) the sha256 comes out to `7892df5a8e0fd83cd5b9ce3d85921a3a4a432bd02fa80d30c21c4d5bf1281a08`.
2. For `Doom 32X - Delta Edition - Episode 1 (Japan, USA) (Hack) v1.0 Roeblez.32x` (and Episode 3) I get a different checksum after applying the author's patch, but Episode 2 does match. How did you apply these? Also, the author's name should be spelled [Roebloz](https://www.doomworld.com/profile/30346-roebloz/).
3. For `Ultimate Doom 1 & 2 All Episodes + Addendum (Japan, USA) (Hack) v1.03 e-Doctor.32x`, I see the [original hack](https://www.romhacking.net/hacks/5446/) but I can't find a matching addendum. But applying the author's single patch to the original rom results in the correct checksum so maybe there isn't actually an addendum?

**Comment by hotelvictorcharlie** [comment]
Also, there's an extra space before the file extensions in `Doom 32X - 24 Levels expansion + Addendum (Europe) (Hack) v1.1 Saxman & Nuxius .32x` and `Mortal Kombat II - Ultimate Edition Improvements (Europe, Japan, USA) (Hack) v1.0 Linkuei .32x`.

**Comment by blinard-BIOINFO** [comment]
Hi, thanks for the report. 

point 3 : I actually kept the original spelling from the database. True, the "addendum" may be confusing as this doesn't match the current romhacking.net entries, and could be removed.

For points 1 and 2, I will have a look at my files during the week-end and push corrections if needed.

**Comment by blinard-BIOINFO** [comment]
@hotelvictorcharlie 
The Delta hack versions are indeed very confusing and the author does not clearly explain which patch is which version.
Here is what I tested : 
| hash | Delta episode | source | version ?? |
| -- | -- | -- | -- |
| 2274065bd2fd47396c1a79bd35912ae0ee5935f0a91d59859a74b1106afd3b18 | 1 | doomworld | this may be old v1.0 |
| f1deadad3f7ad6115dfb35147cf1b98dca29c0073e4f6c29cf11be4559782b2b | 1 | romhacking | v1.0 ? but  release date matches more recent doomworld release v2., e.g. 2021-04-23)|
| 330546cafb9c8ca6aee917f64ad767ecb220176bff3f21e4d1ac3237f4ac962a | 2 | doomworld | this may be old v1.0 |
| 330546cafb9c8ca6aee917f64ad767ecb220176bff3f21e4d1ac3237f4ac962a  | 2 | romhacking | v1.0 ? but  release date matches more recent doomworld release v2., e.g. 2021-04-23) |
| 468a823576353ea3e5e1c0812811356bd02d296d4ce11edb5fc13e6d409a1581 | 3 | doomworld | this may be old v1.0 |
| 3eeee5b8d6e829054790aa5071494b279898e0cfcd2dc203292f0ad512f1f8ad | 3 | romhacking | v1.0 ? but  release date matches more recent doomworld release v2., e.g. 2021-04-23) |
| 784d5c66ac732a6b9057f7ea1bd3e2bb1c4bf893c3f875e3ef91ccd12203402a | 4 | romhacking | v1.0 ? but  release date matches more recent doomworld release v2., e.g. 2021-04-23) |
| 32795b236c9665b838ba4d0fd5576bbc4fe88a1a5274338d1955c2089ec05a0c | 5 | romhacking | v1.0 ? but  release date matches more recent doomworld release v2., e.g. 2021-04-23) |

**Comment by blinard-BIOINFO** [comment]
@hotelvictorcharlie 
I suppose the best would be to fit all to the romhacking entries, they are likely to be maintained on a longer term.

**Comment by blinard-BIOINFO** [comment]
@hotelvictorcharlie 
I did the other corrections following your comments.
https://github.com/blinard-BIOINFO/Hardware-Target-Game-Database/tree/2021_32x_hacks

If you also think that using the Delta hacks from romhacking.net, keeping them as a v1.0 label is the good approach, I will correct them and do a new merge request.

**Comment by hotelvictorcharlie** [comment]
Thank you @blinard-BIOINFO, this all sounds good to me. cc @tjanas & @frederic-mahe

**Comment by tjanas** [comment]
Create a pull request and we can review?

**Comment by Infinitum8t** [comment]
This is impressive work @blinard-BIOINFO and @hotelvictorcharlie.

Going through this entire update and found that Doom 32X Resurrection has now been updated to v1.5 as of December 10, 2021. The hack for v1.3 is no longer on https://www.romhacking.net/hacks/6269/.

I found the hash to be 47196047A6ED406A262F40C270EF7FCEE43162173939BB1706DA0CDAA4940AFC.

**Pull request merged**
