### PR TITLE
Atari 2600: Fix duplicate Galaxian Invaders

### PR DESCRIPTION
**Pull request by birdybro**
Temporary fix for the naming issue here, I was unable to determine there was any difference between these two roms other than their hashes. 

Whoever originally added these two versions ideally should show what the differences are for them to be distinguished later. They might be different versions or different methods of patching the same game. Both play identically from what I can tell on the Atari2600 MiSTer Core.

### CODE REVIEW

**Comment by birdybro** [comment]
Side note, not sure how to fix my endless chain of commits on new pull requests... X_X

**Comment by tjanas** [comment]
> Side note, not sure how to fix my endless chain of commits on new pull requests... X_X
> 
> Going to do that before I submit any further PR's in the future.

No worries, I squash them down to a single commit when I merge them. Are you syncing the branch in your fork with the master branch here before creating your pull request branch from it?

**Comment by tjanas** [comment]
Curious if this patch can be found on atariage, and if so, try to patch it yourself and see if it matches either one. If so, author and version/date info could be added to the file.

**Comment by tjanas** [comment]
https://atariage.com/forums/topic/123913-galaxian-invaders/?tab=comments#comment-1504401

There are two versions here (the 2008-04-19 one, and the 2008-04-20 one with some additional cosmetic changes).

**Comment by birdybro** [comment]
Thank you for finding that.

Renaming to show the difference. I tested them, the latter one (with the two spaces) does have the alternate font at the top, and the legs move when the aliens move from side to side. Pretty cool actually :)

I believe this looks okay. I really couldn't think of a better description for the leg physics, that's what they appear to me to be :P

**Comment by tjanas** [comment]
How about we rename the three files to these (includes authors and dates and filenames are concise)

Galaxian Invaders (Hack) cosmosiss 2008-04-07.a26

Galaxian Invaders No Border (Hack) neotokeo2001 2008-04-19.a26

Galaxian Invaders No Border+ (Hack) neotokeo2001 2008-04-20.a26

**Comment by birdybro** [comment]
Sounds good to me.

**Pull request merged**
