### PR TITLE
 Atari 2600 SMDB: Fix alphabetical order

### PR DESCRIPTION
**Pull request by birdybro**
Just ran the parse on my collection and it turns out the SMDB was out of alphabetical order.

### CODE REVIEW

**Comment by birdybro** [comment]
Oh wait, nvm, not sure why this is happening. Must be a case sensitive issue with the parse tool?

**Comment by birdybro** [comment]
Okay that fixed the issue, didn't notice the random spaces before the .a26 on the other galaxian invaders hack.

**Comment by tjanas** [comment]
@birdybro is this ready for merge?

**Comment by birdybro** [comment]
Yes, sorry I wasn't as clear. :)

**Comment by Infinitum8t** [comment]
After correcting the spaces in the filename "Galaxian Invaders No Border .a26", now there's two files with the same name within the same directory.

2632607010798e8b86233ab85a156357e95956b48823d7622d1719c0af504a4b	Atari 2600/4 Homebrew/AtariAge Homebrew & Hacks/Galaxian Invaders No Border.a26	9cd105a042e0ca409e46ae7f72b14e5c37b9004a	34a211ca507e0a83debd5bf2aa5b4bb1	72bd4be0
bbea6f8db134ee96c7bd5687dd6d30866437a3593df0077dc52f7c8d19648aa2	Atari 2600/4 Homebrew/AtariAge Homebrew & Hacks/Galaxian Invaders No Border.a26	655397eb4093c5d54c8c443483c7eda5a3230c63	90f74aa3ceb941b63b2b47f678a5d668	6413d0b9

**Comment by tjanas** [comment]
@birdybro can you fix this?

**Comment by birdybro** [comment]
Investigating this now. Not sure why they have different hashes, I'll have to find out what the difference between these hacks are.

**Comment by birdybro** [comment]
I see zero difference between how either of these games play. I'll revert the space deletion for now to resolve the doubling up to preserve the original content in case there is an actual difference between these games for someone later to address it.

**Comment by tjanas** [comment]
As previously referenced here https://github.com/frederic-mahe/Hardware-Target-Game-Database/issues/568

**Pull request merged**
